### ISSUE TITLE
CTRLR crashes using getPropertyName on uiEnvelope

### ISSUE THREAD

**Issue by jpw** [RomanKubiak/ctrlr#10]
Hi there! I am trying to see to what extent uiEnvelope works, by interrogating the object and seeing what properties it has.  The eventual aim is simply to get and set points. Thanks.

Where dco is a reference to my uiEnvelope instance:

	dco = panel:getModulatorByName("module-dco-" .. tostring(module))

	obtree = dco.getObjectTree(dco)
	numChildren = obtree.getNumChildren(obtree)

	for i=0,numChildren do
		child = obtree.getChild(obtree, i)
		--what(child)
		--console(child.toXmlString(child)) -- need uiEnvelopePoint ... uiEnvelopePointPosition="19, 89" 
		numProps = child:getNumProperties()
		console(tostring(numProps))
		if numProps > 0 then
			console("got props")
			for propIdx = 0,numProps do
				--console(child:getPropertyName(propIdx)) -- UNCOMMENT TO CRASH
			end
		end
	end

**Comment by RomanKubiak** [comment]
uiEnvelope has been removed long time ago and won't come back in this form ever, so it's hard for me to support it, please move to either a custom component and write the code yourself, or propose a C++ component that will handle an envelope. I'll check on the valuetree stuff to see if there isn't a bug in lua/c++ valueTree binding and if one exists i will fix it.

**Comment by RomanKubiak** [comment]
Oh yeah you can't do: for propIdx = 0,numProps do you are going over the available items in memory, this is lua you need to do:
for propIdx = 0,numProps-1 do
