### ISSUE TITLE
Editor J-Station Johnson

### ISSUE THREAD

**Issue by seve54** [RomanKubiak/ctrlr#113]
Good morning there is some expert who could create editor panel for "J-Station Johnson" for Windows now no longer in production because the official editor is of old conception! Thanks!
![js8](https://user-images.githubusercontent.com/77013086/103767675-5b401000-5021-11eb-90da-f8d42f124114.jpg)
[J-Station En.pdf](https://github.com/RomanKubiak/ctrlr/files/5775703/J-Station.En.pdf)

**Comment by tomlem** [comment]
This is not an issue but a friendly request.
It would best move to discussions / Q @ A

**Comment by shooking** [comment]
@tomlem - great tip on the discussions menu - I never even noticed that until you mentioned it :-)

@seve54 - have you already found this website - seems to be a mine of info.
https://lakecountycomputer.com/j-station/

Looks like most CC's. Shouldnt take you too long to whack up a panel with Ctrlr.

**Comment by RomanKubiak** [comment]
this is not an issue please post this in the discussion section not here
