### ISSUE TITLE
most recent version not starting in Vista

### ISSUE THREAD

**Issue by subv0x** [RomanKubiak/ctrlr#12]
have  deleted ctrl settings file. it hangs. shows 3x ctrlr.exe 
in taskman, can't stop any. won't uninstall, hangs. have to 
delete folder.

**Comment by RomanKubiak** [comment]
I can't support VISTA as i don't own a copy of it nor do i have the resources to test Ctrlr on it. You are on your own in this.

**Comment by subv0x** [comment]
ok no prob; i'm happy checking things out as is at the moment. when i've completed 
current project, i'll find out what the last version i can  run is, and  let you know; i could 
see significant changes by the differences in the  install folder. 

here's a screenshot of what i'm up to, just using very basic skin, figuring out a way to 
work. - i'm getting good feedback on chat, so that is useful.
(see screenshot at foot of emails)
