### ISSUE TITLE
Crash when selecting "MIDI Library" menu entry

### ISSUE THREAD

**Issue by Possemo** [RomanKubiak/ctrlr#120]
Ctrlr Version = 6.0.4
Plugin will crash DAW too. I don't need MIDI Library - does anybody do? My panels do have their own librarians. So, for me and my panels it would be enough to delete the menu entry. If you select it by mistake - crashing the entire DAW - I guess that you won't be amused.
![image](https://user-images.githubusercontent.com/21274845/103900550-34a0d880-50f8-11eb-90d2-11fc6926e6eb.png)

**Comment by dobo365** [comment]
(using 5.3.201)
Never used that and didn't know what it is...
I suppose it was used to see the list of Snapshots?

As a general statement, I think it would be great to be able to select all menu entries that one wants to keep when exporting a restricted instance. There should be a default selection.
Default should be: 
- File-> Quit
- View -> Zoom In, Zoom Out
- Midi -> complete menu
- Tools -> Midi monitor
- Help -> About

**Comment by RomanKubiak** [comment]
new code does not contain the midi library this code has been removed
