### ISSUE TITLE
Can LImage.cpp be added back?

### ISSUE THREAD

**Issue by dobo365** [RomanKubiak/ctrlr#123]
Hi Roman,
  can you add LImage.cpp back (it was in old Sourceforge) or was it some issue with that?
https://sourceforge.net/p/ctrlrv4/code/1511/tree/nightly/Source/Lua/JuceClasses/LImage.cpp 

From within the panel, I'd like to be able to take a screenshot of it and export to a file.
I guess it needs JPEGImageFormat () which is a ImageFileFormat().

I can:
- (OK) create a Rectangle: aR = Rectangle(0,0,200,200)
- (OK) create an Image: aM = panel:getComponent("myPanelTabs"):createComponentSnapshot(aR, false, 1.0)
- (not OK) I need to create an ImageFileFormat()
- (OK) I create a File
- (never tried) I need to create an outputstream for that File with createOutputStream  (is this existing in Ctrlr?)
- (not OK) then that ImageFileFormat can be sent to an outputstream (File) with writeImageToStream

Thx!

**Comment by RomanKubiak** [comment]
Have a look at LGraphics.cpp all the Image class stuff is there now, let me know if there is something missing

**Comment by dobo365** [comment]
Will have a look in 5.3.201 and your new 5.6
