### ISSUE TITLE
Linux build issue - no "make_helpers/arch_detection.cpp"

### ISSUE THREAD

**Issue by tl072** [RomanKubiak/ctrlr#130]
line 51 in ctrlr/Builds/LinuxMakefile/Makefile causes problems with building Ctrlr

make_helpers/arch_detection.cpp does not exist anywhere in the file-system and so building returns with the error: 

makefile target pattern contains no '%'

I replaced line 51 with 

VST3_PLATFORM_ARCH := x86_64-linux and at least now I am getting compile errors :P which I can start to figure out. 

I do not have any knowledge of juce so it may be that somehow the project just needs to be re-build. Anyway, looking forward to playign with Ctrlr once I can build it (the current builds refer to 

./Ctrlr: error while loading shared libraries: libbfd-2.28-system.so: cannot open shared object file: No such file or director

Which is out of date (sorry for the extra bug in this issue - just wanted to explain why I am trying to build it)

**Comment by RomanKubiak** [comment]
a just pushed a re-saved in projucer version maybe it fixes the issue as i'm not observing it at the moment

**Comment by tl072** [comment]
Hi @RomanKubiak - many thanks. This definitely fixed the issue with the Makefile! Some compilation problems with bfd persist but I will look into those and file a separate ticket so that I do not blur what this ticket is about.

**Comment by mtarenskeen** [comment]
I tried building Ctrlr on Fedora 33 and - hurray - compilation process was completed. But unfortunately the resulting Ctrlr binary crashes: 
![Ctrlr-crash](https://user-images.githubusercontent.com/3509304/104911275-e5299a80-598a-11eb-88d3-8c9dd7b7d592.png)

**Comment by tl072** [comment]
@mtarenskeen in a way I think this should be a separate issue but since I also experience a crash on startup, I will mention that I was able to start Ctrlr by removing the settings folder and then restart. It didn't solve everything but it did start up.
