### ISSUE TITLE
idea: Tab Index re-number>move content ?

### ISSUE THREAD

**Issue by subv0x** [RomanKubiak/ctrlr#14]
i'm trying to do this, don't know if it will work:
with 4 tabs, i want to move contents(+title) of #3 to #2, and move 
#2 to #3  > change order 0,1,2,3 to 0,2,1,3 for a better display, 
without having to cut+paste contents and do all the work(!)
maybe if i just renumber tabs,save,close, re-load, it might work..
something one might wish to do in a build, anyway.

**Comment by subv0x** [comment]
ah, it worked.re-numbered, saved, re-loaded, was ok. but 
content didn't move. forget it, i can just changed Ownership 
of elements, i'm sure it'll be ok now.

**Comment by RomanKubiak** [comment]
Please don't post ideas/new-feature-requests etc. here. This place is for bugs and issues.

**Comment by subv0x** [comment]
sure thing
