### ISSUE TITLE
Version numbers in release titles?

### ISSUE THREAD

**Issue by mxmilkiib** [RomanKubiak/ctrlr#142]
Hi, I'd like to aggregate [releases.atom](https://github.com/RomanKubiak/ctrlr/releases.atom) to [libreav.org/updates](https://libreav.org/updates), but the titles that have been given to the releases don't contain the version number so I currently cannot parse that from the releases.atom feed title. Might it be possible to have the version number either at the start or end of the release titles?

**Comment by RomanKubiak** [comment]
i'll add them

**Comment by mxmilkiib** [comment]
That's great, thanks!
