### ISSUE TITLE
i suggest dropping 'save versioning' >  why? >>>

### ISSUE THREAD

**Issue by subv0x** [RomanKubiak/ctrlr#17]
because you never know what you're saving. i version myself, always,  
each time i make significant changes; there is no other way to work. 
but when it opens up something other than what i thought i saved, 
i don't/can't know what's going on. 
however, specifying Ctrlr version with each save, 'under the bonnet', 
in File Properties(etc)is important.
i've just lost a complex panel involving days of work because of this, 
i hope i can get it back by pulling bits out of previous files.(soz, i can't 
make single panel VSTs, too boring :)  )

**Comment by dobo365** [comment]
I personally think this feature should be kept.
BUT maybe that the behavior could be analyzed / reviewed to have it similar to classical MS software for example.
When you save under a version, indeed the version file is created but you stay in the current file.
At next simple Save it is still the original file that is saved.
Is this what we want or shall Ctrlr switch to latest saved file (in this case, the versioned file)?

**Comment by Tonguc-Endem** [comment]
'Save versioned' is a very nice feature.
I always close the panel before exiting and always use 'Save versioned' and never exit and re-launch Ctrlr without closing the panel first. You can not be sure what comes up when you just load Ctrlr and have your panel loaded like that. just properly save with version. It saved my work many times.
