### ISSUE TITLE
Problems with the font changing of the Lua editor

### ISSUE THREAD

**Issue by keinstein** [RomanKubiak/ctrlr#170]
When I open the font change dialog the first time, it does not show the font that is selected on my Linux machine. At least in the first run. 

When I change the font, the cursor disappears. Reloading the panel does not work. I can mark text, but the cursor disappears when I hit any arrow key.

**Comment by Possemo** [comment]
This could be a problem of the newest JUCE library. I too have problems with cursor not showing. In WIN x64 version there is no cursor in the Lua Edtior. Also the Projucer and DemoRunner lacks cursor in some cases. This has been notice by at least one other person - see this post in the JUCE forum: [https://forum.juce.com/t/codeeditorcomponent-caret-not-visible/43330](https://forum.juce.com/t/codeeditorcomponent-caret-not-visible/43330)

**Comment by dobo365** [comment]
In 5.3.201, there is no way to close the Lua editor font window without changing the font.
Can buttons be added: Apply / Cancel or Apply / Close?
The Close window X should simply act as a close without change.

I will also put this as change request / bug. Maybe this has already been handled.

**Comment by keinstein** [comment]
@Possemo since my last upgrade of the Ctrlr code it seems to work. So you were probably right.
@dobo365 this is an unrelatiod issue. If you want to keep your suggestion, please file a different issue.
