### ISSUE TITLE
setProperty does not check validity of the propertyname

### ISSUE THREAD

**Issue by keinstein** [RomanKubiak/ctrlr#180]
It is possible to set invalid property names from Lua. A panel that I use in order to understand how to create a large project with Ctrlr hits thoudsends of juce traps triggered by failed assertions when I load it the first time. More precisely, when it is saved immediately after loading. The reason is that the author of the panel inserts several properties during saving. All these properties have only a numeric id converted into a string. This gets invalid as soon as it is saved in a panel as it is saved as an XML attribute which must not start with a number.

I wonder where else new JUCE properties can be created. If Lua is the only place, it would be sufficient to add a check for XML valid attribute names to the lua wrappers for setPropropery. At least the programmer should be informed that they are doing something invalid.

**Comment by RomanKubiak** [comment]
i removed validation of property names for performance, i left it to the Lua programmer to do validation checks i know you can set invalid names and break Ctrlr. I'm not sure if it's a good idea to add this validation but it might be. Not now too much to fix for now

**Comment by keinstein** [comment]
Please, keep it open. The lua programmer is usually not aware that properties are saved in XML. Currently Ctrlr creates corrupted Panel files. This usually leads to data loss and frustration by users who don't know how to deal with it. At which point were property names validated? How did you do it?
