### ISSUE TITLE
workflow issue (minor)

### ISSUE THREAD

**Issue by subv0x** [RomanKubiak/ctrlr#19]
(sorry if this has been dealt with or mentioned before - am on 5.2.102)

accidental scrolling of values in right-side pane is a problem. 
even if you're aware of the risk, you can still change something 
unintentionally. i have then copied this...hundreds of times.
(wrong 'base fallback value' produced...)

would be better, i think, if you had to click on one of these to activate 
scrolling of value. less risky.

**Comment by RomanKubiak** [comment]
This is fixed a little, only the sliders react to mouse wheel now, the rest of properties remain silet. You can always scroll over the name of the property column and it won;t change anything

**Comment by subv0x** [comment]
hi Roman,hey man, sorry for all the issues ;) 
thanks for looking into it.
Dom
