### ISSUE TITLE
URGENT: please restore the SEND message possibility on the forum

### ISSUE THREAD

**Issue by dobo365** [RomanKubiak/ctrlr#27]
The Send message is not working anymore since several months (tried with Chrome and Firefox).
Most probably an issue with Wordpress.
Could you please look at this and restore so we can send PMs to each other?
Thx in advance!

**Comment by RomanKubiak** [comment]
This should be fixed now, please confirm

**Comment by dobo365** [comment]
Works indeed fine! Thx :)
