### ISSUE TITLE
Upgrade Ctrlr to Lua 5.3

### ISSUE THREAD

**Issue by locurasoft** [RomanKubiak/ctrlr#29]
Lua 5.3 comes with several API and performance improvements. 

It would be great to be able to access that functionality in Ctrlr.

Thanks!
/Pascal

**Comment by RomanKubiak** [comment]
i managed to upgrade to lua 5.3.3 but the bitop library will be lost, there seems to be a war going on between the guy who writes bitop and the lua programmers, anyway 5.3.3 is now in but without bitop i need to do some emulation for it to work (even slower)

**Comment by david-dever-23-box** [comment]
Why not switch over to LuaJIT?

**Comment by RomanKubiak** [comment]
i remember there was an issue with LuaJIT and luabind/boost, but i migt re-consider that. i need to check if that's a good option. i'm testing lua 5.3.3 and i'm getting loads of problems...

**Comment by locurasoft** [comment]
Hi,

I have also become a bit reluctant to Lua 5.3... 

When looking at the integrations with Lua on these pages:

http://lua-users.org/wiki/LuaAddons
http://lua-users.org/wiki/LibrariesAndBindings

It is striking how few integrations there are to Lua 5.3 compared to 5.2 and 5.1. Lua 5.3 has been out for a while now and still the interest for it seem quite weak.

From what I have understood LuaJIT replaces luabind/boost (or at least it doesn't have the boost dependency as luabind does). LuaJIT seems to be maintained by the same guy maintaining the Lua bit library hence it will probably not be ported to 5.3 either.

Perhaps a better alternative for Ctrlr is to stick to 5.1 or potentially upgrade to 5.2.

BR
/Pascal

**Comment by RomanKubiak** [comment]
It seems that it's upgraded and working.
