### ISSUE TITLE
suddenly no more dw8000 functionality

### ISSUE THREAD

**Issue by wertstahl** [RomanKubiak/ctrlr#342]
it worked fine with my Korg DW8000 which is in totally fine condition (just upgraded, everything 100% with midi input from DAW) but i had trouble getting sequencing from DAW and parameter control in line and all of a sudden Ctrlr wont change any parameters in my synth anymore, although the midi monitor in Ctrlr displays sysex going out just fine. 
It is like a minute ago it worked, and all of a sudden it doesnt work anymore. 
I have no idea how to troubleshoot this. Even the "load" button, which gets the parameters from the synth doesnt work anymore.
(I reinstalled, tried all the VST versions, too... it's just as if the DW 8000 suddenly has gone sysex-deaf, although i can send normal midi through my DAW as usual... Sysex is still working on the Synth though...) (Windows 10 Pro, multiple synths work fine through Midi, actually everything works except Ctrlr just stopped having any effect)

**Comment by wertstahl** [comment]
and now, all of a sudden, it works again. all i did was wait for 10 minutes whilst typing my issue and badabing.... can there be some kind of super long buffer issue?

**Comment by wertstahl** [comment]
and 15 minutes later it doesn't work anymore. i just rebooted the computer, turned the synth off and on again and i get nothing. :-/

**Comment by wertstahl** [comment]
also i get an "Access violation at address 000000000040425F in module 'ilbridge.exe'. Read of address FFFFFFFFFFFFFFFF.
each time i exit my DAW.

**Comment by wertstahl** [comment]
and after that - all of a sudden, reload project, and it works again.

**Comment by wertstahl** [comment]
also, is it normal that i cannot automate any of the parameters?

**Comment by wertstahl** [comment]
i just understood this might be the wrong place for voicing the issues i had with Ctrlr and Korg-DW-8000.bpanelz ... sometimes it works, sometimes it doesn't. i cannot replicate why the stopping of functionality occurs. therefore i close this issue.

**Comment by dobo365** [comment]
In fact, you should first try to contact the person who made the panel or take it and try to find the issue by yourself.
About automating parameters, this is done by your DAW after exporting a VST version of the panel (open Ctrlr within your DAW then open the panel in that Ctrlr instance then export as restricted instance to have a VST).
Best...
