### ISSUE TITLE
Please add docs on building

### ISSUE THREAD

**Issue by mschuerig** [RomanKubiak/ctrlr#35]
I haven't found any docs on how to build ctrlr on various platforms and from the sources alone I don't get it. I've seen a .sln file, presumably for Visual Studio, but that doesn't help me much on Linux.

I thought I'd be able to figure this out, apparently I'm not, so I have to ask for additional docs or a pointer to existing ones I might have missed.

**Comment by RomanKubiak** [comment]
Added some build instructions for each platform to the README.md file
