### ISSUE TITLE
5.3.201 Exporting to VST results in an empty Ctrlr instance.

### ISSUE THREAD

**Issue by Sebo1971** [RomanKubiak/ctrlr#355]
Hi:
I made a panel and succesfully exported to .exe from the standalone Ctrlr 5.3.201 and it works with no problems.
I open the VST plugin in Cakewalk by Bandlab, load the panel and change the ports routing. It works right that way.
Then I try to export it (Export instance) and succesfully created a .dll, but when I open it in Cakewalk it opens as an empty Ctrlr instance (no panel at all), just lik when I open the Ctrlr plugin.
I assigned a "Unique Panel ID for Plugin Instances" and also a "Unique Panel Manefacturer ID".
Also I tried doing it from Ableton Live with the same results...
I'm on Windows 10 64bits.
Can anybody tell me what I'm doing wrong?

**Comment by dobo365** [comment]
Hi. I'm doing this all the time without any issue so we'll find a solution ;-)
Try exporting a Restricted instance from the VST plugin. Maybe it will be different.

The other point and maybe this is the reason of the issue is that even if you indicate a "Unique Panel ID for Plugin Instances" it will not be exported/written in the created plugin and CTRL wil be used. You need to change that manually.
To do that:
- download HxD which is an hexa editor
- open your plugin
- search for LRTC (plugin ID's are written in an opposite way)
- replace by the ooposite way you wanted to have. So, if you want AbCd, write dCbA
- save 
You can do all of this while keeping Cakewalk open. It refreshes the plugin each time.

Good luck

**Comment by Sebo1971** [comment]
Hi dobo365,
Thanks for your response.

I tried exporting a Restricted Instance and I have the same result.

Also tried editing the .dll with HxD, I reeplaced LRCT with 2BTM (I wanted MTB2). And it didn't worked.

I forgot to mention before that after exporting the instance I'm having this error message:

"Failed to export panel as standalone instance.
Windows Native: exportMeWithNewResource BeginUpdateResource failed"

But the plugin is export anyway.
I didn't mention it because when exporting the instance from the standalone I have a similar error message and it worked anyway.

**Comment by dobo365** [comment]
OK.
That message is usually coming from the fact that you are exporting in a directory where an authorization is needed. 
On Mac for example, you need to enter the admin password to write in the AU or VST plugins directories.
Store your plugin in "My Documents" or equivalent then move it where it should be.

In general (valid for any system), you should avoid error messages even if things looks OK.
You never know what's happening in the background ;-)

**Comment by Sebo1971** [comment]
Hi, I exported it to My Documents and I'm having the same error message.
Also the plugin didn't work.

**Comment by Sebo1971** [comment]
I don't know what else can I do.

If I send you the panel, could you try to export it as VST for me?

**Comment by dobo365** [comment]
Sure! sunny.synths@gmail.com

**Comment by Sebo1971** [comment]
I realized that exporting from the standalone version is not working either (it just open a Ctrlr instance, but as it loads the last panel, I though it was working).

I don't know if this could be the problem, but I initially instaled ver 6.0.26, then after having some trouble I read that I should use ver 5.3.201. I started my panel from scratch with this version, but maybe the previous install left something that is causing problems...

If you can export the panels for me it will be great.
Here are the panels:
https://drive.google.com/file/d/1e6PVt3eZ4UpfUE_AHqWPRlIJMmKbwQMt/view?usp=sharing
There are 4 files in the zip:
2 versions of the panel and a standalone and VST version for every version.
Please, can you export the VST of the 2 files that says VST, and export the standalone of the other 2 files?
Thank you very much!!!

**Comment by Sebo1971** [comment]
Ohh, I just realized you posted an email adress, I will write to you there.
Thanks!

**Comment by dobo365** [comment]
Problem solved. When I saw the panels I directly suspected the issue...
The panel name is MFB Tanzbär and **the ä is not well appreciated**.
Just replace Tanzbär by Tanzbar and the problem will be solved.
Enjoy!

**Comment by Sebo1971** [comment]
It is working!!! Thank you!!!

I feel like an idiot because my mother languge is Spanish and always avoid to use the "ñ" and the accents because cause problems, but I totally overlooked the "ä"
