### ISSUE TITLE
malfunction method String:startsWith ("...") in every Win32 Build above 1590

### ISSUE THREAD

**Issue by rahno** [RomanKubiak/ctrlr#36]
```
testString = "Efx1_High"
compareString = "Efx1"
result = tostring(String(testString):startsWith( compareString ))
console (string.format( "%s startsWith %s == %s", testString, compareString, result ))
```

output:
`Efx1_High startsWith Efx1 == false`

ref: http://ctrlr.org/forums/topic/bug-tested-same-panel-with-win32-and-x64-ctrlr-scripts-malfunction/#post-70103

**Comment by RomanKubiak** [comment]
can you try this:

```
haystack = String("haystack")
ret = haystack:startsWith("hay")
if ret == 0 then
	console ("ret is 0")
else
	console ("ret is 1")
end
console (string.format("%s", ret))
```
i think that the string.format function is lying to us, but the result is fine i think.

**Comment by rahno** [comment]
```
haystack = String("haystack")
ret = haystack:startsWith("hay")
if ret == 0 then
    console ("ret is 0")
else
    console ("ret is 1")
end
console (string.format("false = %s = %s", tostring(false), tostring(0)))
console (string.format("true = %s = %s", tostring(true), tostring(1)))
console (string.format("ret = %s", tostring(ret)))
```


win32

> LUA>> ret is 1
> LUA>> false = false = 0
> LUA>> true = true = 1
> LUA>> ret = false


x64

> LUA>> ret is 1
> LUA>> false = false = 0
> LUA>> true = true = 1
> LUA>> ret = true

**Comment by rahno** [comment]
your if statement is wrong..

it should be compared with true and false:

`haystack = String("haystack")
retone = haystack:startsWith("hay")
if retone == 0 then
    console ("retone is 0")
elseif retone == 1 then
    console ("retone is 1")
elseif retone == true then
    console ("retone is true")
elseif retone == false then
    console ("retone is false")
else 
    console ("retone is not 0 nor 1 nor true nor false")
end
rettwo = haystack:startsWith("hay2")
if rettwo == 0 then
    console ("rettwo is 0")
elseif rettwo == 1 then
    console ("rettwo is 1")
elseif rettwo == true then
    console ("rettwo is true")
elseif rettwo == false then
    console ("rettwo is false")
else 
    console ("rettwo is not 0 nor 1 nor true nor false")
end
console (string.format("false = %s = %s", tostring(false), tostring(0)))
console (string.format("true = %s = %s", tostring(true), tostring(1)))
console (string.format("retone = %s", tostring(retone)))
console (string.format("rettwo = %s", tostring(rettwo)))`


win32

> LUA>> retone is false
> LUA>> rettwo is false
> LUA>> false = false = 0
> LUA>> true = true = 1
> LUA>> retone = false
> LUA>> rettwo = false

x64

> LUA>> retone is true
> LUA>> rettwo is false
> LUA>> false = false = 0
> LUA>> true = true = 1
> LUA>> retone = true
> LUA>> rettwo = false

**Comment by RomanKubiak** [comment]
Well this looks like a problem with string converters and the appearance of StringRef, i think i fixed it but this is up for review later
