### ISSUE TITLE
fixed small window under linux (x64)

### ISSUE THREAD

**Issue by nielsd** [RomanKubiak/ctrlr#37]
Hiho,

i tried to start the current Ctrlr (binary) under a current Gentoo Linux. The program starts, but just show a very small quadratic segment of the upper left window which doesn't seem resizable - so Ctrlr seems not usable att on this platform.

Are there any sources for trying a self build?

If you need any system / environment details pls feel free to ask.

many thanks,
best regards,

Niels Dettenbach
http://www.syndicat.com

**Comment by RomanKubiak** [comment]
This should now be fixed in the source tree.
