### ISSUE TITLE
Newer binutils version need config.h

### ISSUE THREAD

**Issue by arcangeli** [RomanKubiak/ctrlr#38]
Newer version of binutils need config.h or #define PACKAGE "Ctrlr" to be set.
Compiling CtrlrLinux.cpp
In file included from ../../../../Source/Misc/include/libr.h:30:0,
                 from ../../../../Source/Native/CtrlrLinux.cpp:13:
/usr/include/bfd.h:35:2: erreur : #error config.h must be included before this header
 #error config.h must be included before this header
Same with Source/Misc/libr.c and Source/Misc/libr-bfd.c

Work around: add #define PACKAGE "Ctrlr" just after #ifdef LINUX

**Comment by RomanKubiak** [comment]
added
