### ISSUE TITLE
release 5.4.16: calc with getProperty values instead of getPropertyInt values will crash Ctrlr

### ISSUE THREAD

**Issue by Possemo** [RomanKubiak/ctrlr#39]
in release Ctrlr-5.4.11 it still worked. In release Ctrlr-5.4.16 "uiListBoxItemClicked" won't execute the attached script. Same with "luaModulatorValueChange".

**Comment by RomanKubiak** [comment]
Well i can't confirm that i just checked the windows build, and the listbox behaves as it should all actions are triggered and lua works fine. Can you attach a simple example panel that has this bug ? Also what platform are you using ?

**Comment by Possemo** [comment]
Hi Roman, thanks for your reply. I am on Windows10.

I finally found out what's the problem. uiListboxes are working correct. In the script I am using _G[..] to compose a name of a table:

BufferTab=_G["Preset"..nr.."TableNr"..p]

This will select a table according to the variables nr and p. For example it could be Preset2TableNr68. This is not working anymore in the new release. On the other hand, composing with only one variable still works - e.g. _G["Preset2TableNr"..p].

Is this a "feature" of the new Lua version or ist it a bug of Ctrlr?

Thanks for spending time on this issue.

Chris

**Comment by Possemo** [comment]
I changed the description of the issue. I don't have much scripts where I am using more than one var for a dynamic variable name, I will change the ones that do. So, if you want you can delete this issue. Sorry for bothering.

**Comment by Possemo** [comment]
It's me again. It was all wrong. I think I now definitely found the culprit. Sorry for making such a mess...

It was partially a fault of myself. I did get Int values with getProperty(..) and made simple calcs with them. When I am using getPropretyInt instead (as intended I guess) it is all well. Calcing with getProperty values will produce a  value that will crash Ctrlr without warning when using it wherever. So this should probably be handled in some way by Ctrlr. It worked without a problem in release 5.4.11 (it probably assumed that the value is an Int value).

Here an example (test panel is attached to this message):

myNewMethod = function(--[[ CtrlrModulator --]] modulator, --[[ number --]] value)

	p=20
	nr=modulator:getProperty("modulatorCustomIndexGroup")**-100**

	console(string.format("nr is %d",nr))
	console(string.format("p is %d",p))

	pnr=nr..p

	-- now any operation with pnr will crash Ctrlr!
	-- like this simple one:

	-- console(string.format("%d",pnr))
end

[getPropertyBugTest.zip](https://github.com/RomanKubiak/ctrlr/files/587294/getPropertyBugTest.zip)

**Comment by Possemo** [comment]
It looks like this has been fixed in v5.4.27
