### ISSUE TITLE
release 5.4.16: selecting more than 2 components with ctrl+leftmousebutton will hang Ctrlr

### ISSUE THREAD

**Issue by Possemo** [RomanKubiak/ctrlr#40]
I think it does not matter which components you try to multi-select.
Very simple panel attached with 4 uiLabels. When you select more than 2 labels Ctrlr will hang. This bug has been introduced in v5.4.16.

[multipleSelectBugTest.zip](https://github.com/RomanKubiak/ctrlr/files/587399/multipleSelectBugTest.zip)

**Comment by AlexFundorin** [comment]
I confirm this issue.

**Comment by Possemo** [comment]
still persists in v5.4.27

**Comment by RomanKubiak** [comment]
Should be fixed in the latest build
