### ISSUE TITLE
On Pull Request #400 : build.sh  error `No rule to build target...`

### ISSUE THREAD

**Issue by tomlem** [RomanKubiak/ctrlr#412]
On #400 
- `LANG=C ./build.sh Debug Standalone` results in the error `No rule to build target...` 
  - For debug info:
https://github.com/RomanKubiak/ctrlr/files/7884114/dbg0_buildDOTsh.txt

**Comment by keinstein** [comment]
Can you try it again, please?

**Comment by tomlem** [comment]
@keinstein 
Yes, tomorrow I will do that. 
Today I can't access my PC.

**Comment by tomlem** [comment]
- `LANG=C ./build.sh Debug StandAlone` changes the original makefile. Since the newly created makefile has no target for 'StandAlone', it results in `No rule to make target...`
- `LANG=C ./build.sh Debug`also changes the original makefile, but when no target is specified, the target 'All' is used. This results in a bunch of files which are all for testing purpose. Since 'Standalone' is not among the targets in the newly created makefile, it is not build. See terminal output for this command: 
[Terminal_build.sh_Debug.txt](https://github.com/RomanKubiak/ctrlr/files/7926273/Terminal_build.sh_Debug.txt)
- When `LANG=C ./build.sh` is not executed previously, the original makefile is still present and therefore the command `make CONFIG=Debug -f pchbuild.mk Standalone` compiles without errors.

**Comment by tomlem** [comment]
@keinstein:

- Is a typo the cause? 
Line 8 in CMakeError.log goes as follows: 
`c++: error: unrecognized command-line option '-Wdisabled-optimizations'; did you mean '-Wdisabled-optimization'?`
  - /Buils/LinuxMakefile/CMakeFiles/CMakeError.log: 
[CMakeError.log](https://github.com/RomanKubiak/ctrlr/files/7953279/CMakeError.log)

**Comment by keinstein** [comment]
This should have been fixed in commit 99ba30ac9b1d0f7affb2a67570582a1f289ed5f2

**Comment by tomlem** [comment]
`LANG=C ./build.sh Debug Standalone` now works as it should.

**Comment by tomlem** [comment]
@keinstein 

Discussion about this topic moved to #400.
