### ISSUE TITLE
On pull request #400: Pasting some text in the lua terminal or console fails

### ISSUE THREAD

**Issue by tomlem** [RomanKubiak/ctrlr#417]
On #400 
Pasting some text in the lua terminal or console (from clipboard) using the mouse does not function (no text pasted).

**Comment by keinstein** [comment]
Is it the same as https://github.com/juce-framework/JUCE/issues/1008 ?

**Comment by tomlem** [comment]
Yes, I think so.

**Comment by tomlem** [comment]
@keinstein 
Further discussion on this topic moved to #400
