### ISSUE TITLE
Cannot build on Linux

### ISSUE THREAD

**Issue by Lalarian** [RomanKubiak/ctrlr#419]
Hello!

I was just trying to build latest git clone of Ctrlr, but I could not do it. The instructions didn't seem to fit:
Builds/Generated/Linux/Standalone does not exist.
So I tried Builds/LinuxMakefile/build.sh
```
But this stops with: 
Makefile:336: *** Ziel-Muster enthält kein „%“.  Schluss.
CTRLR[linux]: build failed
```

Then I tried using:
Scripts/post-commit
But this doesn't work because of:
```
In Datei, eingebunden von /usr/include/boost/bind.hpp:30,
                 von ../../Source/Misc/luabind/luabind/class.hpp:94,
                 von ../../Source/Core/stdafx_luabind.h:20:
/usr/include/boost/bind.hpp:36:1: Anmerkung: »#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.«
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
CTRLR[linux]: Build now

Makefile:336: *** Ziel-Muster enthält kein „%“.  Schluss.
CTRLR[linux]: build failed
```
The latest binary from download section doesn't work on my OS, because of libbfd.
What can I do to make it work?
Thank you! :)
```

**Comment by tomlem** [comment]
See issue #358 

Take also a look in #400

**Comment by Lalarian** [comment]
Thank you. I have been using the Windows version in between, in Wine. But it's very slow. So I will see if I can manage to build it now!
