### ISSUE TITLE
Windows xp 32bit builds no longer working.

### ISSUE THREAD

**Issue by ewanuno** [RomanKubiak/ctrlr#46]
In ctrlr 5.4.27 and 5.4.29 On windows xp when i try to open to open the ctrlr standalone it gives me an errror:
'Impossibile trovare il punto di ingresso CreateSymbolicLinkW della procedure nella libreria di colegamento dinamico KERNEL32.DLL'

And ableton fails to load the vsti

In english that's 
'Impossible to find entry point CreateSymbolicLinkW in the dynamic link library KERNEL32.DLL'

it looks to me that something when wrong in  linking.

ctrlr 5.3.201 works though. So this probably happened fairly recently.

Ewan.

**Comment by RomanKubiak** [comment]
XP is not supported anymore
