### ISSUE TITLE
LINUX: issue with Lua Editor cursor position

### ISSUE THREAD

**Issue by rhaamo** [RomanKubiak/ctrlr#49]
version: Ctrlr-x86_64-5.4.16.sh (latest linux from nightly) on xubuntu

I have issue with LUA Editor, the cursor is not on the right place, see screenshots.
![selection_457](https://cloud.githubusercontent.com/assets/8625/23158261/e04640d0-f81e-11e6-90e5-39deeb4fa7de.png)

I have wrote "testtesttest", then clicked on right of the last "t", wrote a "X", then it appeared on the wrong place.

The following screenshot is when just writing "testtesttest" and show the wrong cursor position, which should appears just after the last "t"

![selection_458](https://cloud.githubusercontent.com/assets/8625/23158353/2fd03110-f81f-11e6-9845-61e08e98b9e4.png)

**Comment by RomanKubiak** [comment]
is this still an issue, also what window manager are u using GTK/KDE/LXDE something else, i can't reproduce this

**Comment by RomanKubiak** [comment]
please reopen the issue if it's still there
