### ISSUE TITLE
Cannot call AlertWindow.addProgressBarComponent from Lua

### ISSUE THREAD

**Issue by fredzo** [RomanKubiak/ctrlr#5]
The wrapper for addProgressBarComponent() method on LAlertWindow.cpp cannot be called from Lua because it requires the progressValue parameter to be passed as reference (which is not possible from Lua, unless I'm missing something).

We really need a way to handle progress bars in Ctrlr to give feedback to the user while a long running MIDI operation is being performed. Having it in a modal window seems a good option since we don't want the user to perform other operations while a MIDI dump is in progress.

I've been trying to use the ThreadWithProgressWindow but threading in Lua seems to cause some problems (Ctrlr crashes every once in a while...).

**Comment by RomanKubiak** [comment]
THis might be problematic but i will try to do something that will make a progress bar usable.

**Comment by fredzo** [comment]
That would be great ! ;-)
I'm not sure we need threading for the progress bar : in my case, progress update is triggered by an incoming midi message (ack sent by the device when a frame is received).
You can check my current implementation based on ThreadWithProgressWindow here : http://ctrlr.org/hughes-kettner-grandmeister-36/
The thread method only does that : 
function progressThreadFunction()
     while presetsToSend ~= nil and presetsToSendIndex <= presetsToSendSize do
		lastThreadCall = Time.getMillisecondCounterHiRes()
		sleep(100)
    end
end
It's only used to detect a user cancellation (since putting lua code after the modal window is closed by a user cancel makes Ctrlr crash).

**Comment by RomanKubiak** [comment]
I added a component called uiProgressBar, you can control it using standard Lua methods. Just create one of those on the panel, and set it's value like

c = panel:getComponent("progressBar")
c:setComponentValue (0.5, true) -- for 50%
c:setComponentValue (-1, true) -- to make the progress bar spin
c:setComponentValue (0.1, true) -- for 10%
c:setComponentText("What's up?") -- to set what's displayed on the progress bar

**Comment by fredzo** [comment]
Great, thank you for that !
I just tested it, it works perfectly.
Could you generate an OSX build of the 5.6.32 ?
