### ISSUE TITLE
LINUX: Build broken

### ISSUE THREAD

**Issue by rhaamo** [RomanKubiak/ctrlr#50]
Hello,

Linux native build seems broken, and documentation not up to date.
Some things I have needed to do but still not successfull:

- Tried commits up to 63282781d52b897f117b2a45dc36ab2a08535e75 and can't build at all
- Needed to ```unzip boost.zip``` in ```<repo>/Source/Misc/boost/``` and ```<repo>/Boost/```
- Use "bash build.sh" in ```<repo>/Builds/Generated/Linux/Standalone/``` and not ```chmod +x build.sh && ./build.sh```
- In build.sh and Makefile change ```-I ../../../../Juce/modules \``` to ```-I ../../../../JUCE/modules \``` (case sensitive)
- In build.sh add to ```-I``` list: ```-I ../../../../Source/Misc/luabind \``` and ```-I ../../../../Source/Misc/lua/include \```
- In Makefile, add to the three ```JUCE_CPPFLAGS``` list the following: ```-I../../../../Source/Misc/lua/include -I../../../../Source/Misc/luabind -I../../../../Source/Misc/liblo/include/```

With theses changes I am able to build to a certain point but it always fails.

Master currently fails on:
```
Compiling CtrlrProperties.cpp
Compiling CtrlrSysexProcessor.cpp
Compiling CtrlrSysexToken.cpp
Compiling CtrlrUpdateManager.cpp
../../../../Source/Core/CtrlrUpdateManager.cpp: In member function ‘virtual void CtrlrUpdateManager::timerCallback()’:
../../../../Source/Core/CtrlrUpdateManager.cpp:91:30: error: ‘ctrlrCheckForUpdates’ is not a member of ‘Ids’
  if ((bool)owner.getProperty(Ids::ctrlrCheckForUpdates) == false)
                              ^~~
../../../../Source/Core/CtrlrUpdateManager.cpp: In member function ‘juce::XmlElement* CtrlrUpdateManager::getUpdateData(const juce::String&)’:
../../../../Source/Core/CtrlrUpdateManager.cpp:108:32: error: ‘ctrlrUpdateUrl’ is not a member of ‘Ids’
   url = URL(owner.getProperty (Ids::ctrlrUpdateUrl));
                                ^~~
Compiling CtrlrUtilities.cpp
Makefile:472: recipe for target 'build/intermediate/Release_Nightly/CtrlrUpdateManager_a061528e.o' failed
make: *** [build/intermediate/Release_Nightly/CtrlrUpdateManager_a061528e.o] Error 1
make: *** Waiting for unfinished jobs....
CTRLR[linux]: build failed
```

Edit: error seems related to 315843ae77d37b819abfe3a6764a4065ddefe060

(ugly) removing the impacted lines it build and leads to:

```Compiling CtrlrLuaFile.cpp
Compiling CtrlrLuaMemoryBlock.cpp
make: *** No rule to make target '../../../../Source/Lua/luabind/src/luabind.cpp', needed by 'build/intermediate/Release_Nightly/luabind_8688111a.o'.  Stop.
make: *** Waiting for unfinished jobs....
Compiling CtrlrLuaRectangle.cpp
CTRLR[linux]: build failed
```

luabind.cpp doesn't exists
Seems related to 3b4bbc714a47c4cb31eccf6b0951f9a1401c4c9b which change luabind to a fork without luabind.cpp

(now I'm stuck :p)

**Comment by vredeling** [comment]
This goes for the Mac build as well.

**Comment by danielappelt** [comment]
Hey there! Could you please provide the files to build the linux version? They are at least missing since the latest (tagged) release v5.5.

**Comment by dcoredump** [comment]
Hi, build.sh is still missing :-(

**Comment by gatesphere** [comment]
+1 -- can't build on Arch Linux:

```
[asdf@oath Scripts]$ bash post-commit
CTRLR pre-commit HOOK
post-commit: line 68: /home/asdf/src/ctrlr/Scripts/..//Scripts/git-revision.sh: Permission denied
CTRLR: build_now_linux
CTRLR: CTRLR_ROOT /home/asdf/src/ctrlr/Scripts/../
----------------------------------------
	Version: 
	CtrlrRevision.template: /home/asdf/src/ctrlr/Scripts/..//Source/Core/CtrlrRevision.template
	CtrlrRevision.h: /home/asdf/src/ctrlr/Scripts/..//Source/Core/CtrlrRevision.h
	Date: Tue Jun 12 18:48:43 EDT 2018
----------------------------------------
CTRLR: Delete binaries
CTRLR: check if boost is unpacked
CTRLR: need to unpack boost.zip
post-commit: line 329: cd: /home/asdf/src/ctrlr/Scripts/..//Boost: No such file or directory
CTRLR: boost.zip file does not exist, exiting now
```

**Comment by RomanKubiak** [comment]
New versions with updated build scripts and makefiles are now available, first binary build is now uploaded.
