### ISSUE TITLE
Crash opening MINIAKmicron.bpanelz

### ISSUE THREAD

**Issue by ulbo** [RomanKubiak/ctrlr#51]
OS: Ubuntu 16.04
Linux diamond 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Panel: http://ctrlr.org/akai-miniak-alesis-micron/
http://ctrlr.org/?ddownload=14924

Crash file attached
[Ctrlr-x86_64.crash.txt](https://github.com/RomanKubiak/ctrlr/files/876709/Ctrlr-x86_64.crash.txt)

**Comment by RomanKubiak** [comment]
latest binary does not crash, however there is an error in Lua code, this needs to be forwarded to the panel's author
