### ISSUE TITLE
Custom Icon for exported Instances

### ISSUE THREAD

**Issue by fredzo** [RomanKubiak/ctrlr#6]
It would be nice if we could provided a custom Icon to be used when generating an exported instance (.exe or .app files with an icon different from the default Ctrlr icon).

**Comment by RomanKubiak** [comment]
This will never be added. On each platform that supports icons in binaries you can change them yourself, on the mac all you need to do is replace the .icns file in the package and on windows use any free resource editor and place any icon you want in the binary.
