### ISSUE TITLE
 For us design luvvers that do get itchy...

### ISSUE THREAD

**Issue by bijlevel** [RomanKubiak/ctrlr#622]
Just to add, as an addition for us design luvvers that do get itchy when seeing the atrocious flat designs Juce drops on us but we can apply a custom L&F by putting in an init file:

```
lf1 = LookAndFeel()
lf1:setImplementation (slidLF1)
panel:getComponent("slid1"):setCustomLookAndFeel(lf1)
```

and then create an L&F by adding a method, in this case, called slidLF1.
```
slidLF1 = {drawRotarySlider = function(g,x,y,width,height,sliderPosProportional,rotaryStartAngle,rotaryEndAngle,slider)
//Do a paint routine for a rotary slider
end,
}
```

So, if you create a script called slidLF1, slidLF2, slidLF3, and so on, you can attach different L&F to different sliders.  Example: This is done on a rotary slider with custom L&F:
![slid](https://github.com/RomanKubiak/ctrlr/assets/71118185/9b41fcb5-d349-4f49-9d82-5db9985abd39)

_Originally posted by @Ted-juh in https://github.com/RomanKubiak/ctrlr/discussions/596#discussioncomment-8152942_

**Comment by bijlevel** [comment]
@Ted-juh Leef je nog?😋
I have studied your post above about the custom rotary slider, because I like the design and I'm at the moment busy with a panel design. Am I right in my understanding that the outer red ring is a L&F v4 slider and the rest a "painted" rotary slider. So a combination? Could you please post a panel with this slider. This is wat I'm aiming at (very roughly...)

<img width="140" alt="custom rotary" src="https://github.com/RomanKubiak/ctrlr/assets/11859363/a42b093f-c50a-4221-9ea0-7d83b70e641d">

**Comment by Ted-juh** [comment]
Yeah, still alive but very busy with my Ctrlr extension which is still in testing stage. 

As far as I can remember it's all done with l&f. The only moving part in this slider is the little red stripe on the second to last ring which will be the white ball in your slider. The "outer" red ring is a pie segment done with radians. 

I'm at work at the moment but will look for the code when I get home.
