### ISSUE TITLE
OSC support

### ISSUE THREAD

**Issue by AlexFundorin** [RomanKubiak/ctrlr#65]
A year passed since the last time OSC functionality was discussed on the forum. Since then, Roman decided to implement native Juce OSC library. Last few releases had OSC part completely broken. I wonder, if there are any plans to finally add OSC support during this year?

**Comment by AlexFundorin** [comment]
Good to see that this issue is still considered.

**Comment by rekliner** [comment]
Build 5.4.29 from 2017-Apr-07 has working OSC functionality (at least on win32) if you need it.  As of 5.5.2 on May 8 it's still broken but I too am glad to see that Roman has put it in Major Tasks.
