### ISSUE TITLE
Plenty of undefined values on my VST2 export

### ISSUE THREAD

**Issue by dervur** [RomanKubiak/ctrlr#654]
Hello there,

Is it normal that there are plenty of undefined values as the controllable values for automation in Cubase? I only have one knob in the project, but I can see 64 parameters (the list of undefined goes up to 63, plus the actual knob with its name).

![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/688b6b51-37b3-4644-89ef-3b15dcf92744)

Just to specify this is on the restricted export version of the dll, I was just doing some tests with only one knob because I had the same issue on another project and I can't understand if it has something to do with the settings I have or not. Because I changed the VST index in order to have the order as I want it. But I noticed that if I just copy paste the knob on a new project the default VST index is 57, so I don't know if this is the issue.

**Comment by damiensellier** [comment]
Not sure if it's going to work but there's a general property called "max Exported VST Parameters" in the Ctrlr Preferences. Try if you could change it to 1.

![Capture d’écran, le 2024-06-27 à 14 16 51](https://github.com/RomanKubiak/ctrlr/assets/55164385/07e9243e-aab9-47de-af6a-53c9fb120aea)

**Comment by dervur** [comment]
Mmmh I will try that, I have to say though that I left that unchanged and once I added more than 64 parameters I found myself with all the parameters (around 160), the only unassigned left was the 0 one because I began from VST index 1, but that's fixable, easily but will take me long since I have to do them one by one...

**Comment by damiensellier** [comment]
That's right, VST Index 0 is skipped in Cubase and first parameter will be 1 which is strange.
The problem is that all VST daws don't work this way and don't respect the VST nomenclature. So the 1 parameter would be skipped if I start at index 0 to please Cubase. That's a dilemma :)

**Comment by damiensellier** [comment]
SEE : https://forums.steinberg.net/t/vst-index-for-parameters-starts-at-0-or-1/833462

**Comment by dervur** [comment]
Uh, that's weird lol, good I distributed my VST2 in a few forums with nothing assigned at index 0 then... I'll try tomorrow for the other unassigned values and in case I'll mark this issue as solved.

**Comment by dobo365** [comment]
Indeed, you need to adapt your Export flag and renumber components according to the order you want to see them in the DAW.
If we assign from 1 then 0 may be listed as "undefined" if the DAW lists from index 0. Not a real issue, imho
If you assign 3000 to 4000 then you will get 2999 undefined.

**Comment by damiensellier** [comment]
I just checked and the index starts at 0 for vstindex 0, It was my mistake to start my index from 1 this is why I had undefined_0 on index 0:
![Capture d’écran, le 2024-06-28 à 12 21 37](https://github.com/RomanKubiak/ctrlr/assets/55164385/35e0f448-fb46-4676-9ff0-1dc39a22d1c2)


![Capture d’écran, le 2024-06-28 à 11 58 40](https://github.com/RomanKubiak/ctrlr/assets/55164385/8666d07e-3740-49f1-a41e-81c37b4005f8)


If you need to reassign all your modulator vstindex just use the modulator list or copy paste the xml file of your panel and ask gemini or chatGPT to decrease the value of vstindex by 1.

**Comment by dervur** [comment]
> Not sure if it's going to work but there's a general property called "max Exported VST Parameters" in the Ctrlr Preferences. Try if you could change it to 1.
> 
> ![Capture d’écran, le 2024-06-27 à 14 16 51](https://private-user-images.githubusercontent.com/55164385/343899322-07e9243e-aab9-47de-af6a-53c9fb120aea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NDM2NjcsIm5iZiI6MTcxOTk0MzM2NywicGF0aCI6Ii81NTE2NDM4NS8zNDM4OTkzMjItMDdlOTI0M2UtYWFiOS00N2RlLWFmNmEtNTNjOWZiMTIwYWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE4MDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzRkM2IzMjViZTFkNDg2YmQ2MmJhNjAyYWU5NjE0YjZjYWQ5OTc4NzdmN2Y4NzJkZjFmMGZmYjgzNDQ3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ry8lklwQHUEXtpXNXN4xuaUF24Vgi6aANmZhTDWmbR8)

It seems that this value is available only in the settings of the .exe but not the .dll
If I change it in the exe, close Ctrlr and reopen it, it seems that the value remains saved.
However, if I open the dll and export my restricted instance, the VST still has plenty of unassigned values. If I then open the exe of Ctrlr, that value went back to 64. Therefore not only the dll does not have that value, it also seems to reset it to its default 64... Is there something I'm missing or is it a bug?

**Comment by damiensellier** [comment]
It's probably a bug. I don't really know how this parameter is supposed to work, especially when it needs to pass the modulators as parameters to the Host in VST.
I'll check that, I'm pretty sure there's a way to iterate through all the modulators and have only the required amount of parameters fixed to the vstindex max value.

**Comment by dobo365** [comment]
Sorry but I don't understand the issue... even if there is maybe a bug with max exported parameters.

I mean: you have a way to control what parameters to export or not and you have a way to sort them as you want by using the VST index (I'm sorting / renumbering them with the Modulator list).
So, what do you want more?
If using max exported parameters, it could be that you are setting some parameters to be exported but that at the end they will not be in the export because you set a limit. Seems more a problem than a benefit.

Is it something I missed or that I don't understand?

**Comment by dervur** [comment]
> Sorry but I don't understand the issue... even if there is maybe a bug with max exported parameters.
> 
> I mean: you have a way to control what parameters to export or not and you have a way to sort them as you want by using the VST index (I'm sorting / renumbering them with the Modulator list). So, what do you want more? If using max exported parameters, it could be that you are setting some parameters to be exported but that at the end they will not be in the export because you set a limit. Seems more a problem than a benefit.
> 
> Is it something I missed or that I don't understand?

Hi, I know that. But if you see in my post I only have one modulator, assigned to index 0 and allowed to be exported as VST… I still have 63 unassigned values exported. So it clearly does not export only the one you ask to, but it also exports a bunch of useless values.
I mean it is not a problem per se, automating those unassigned values would do nothing, it is more of a “it would be nice to have in the list of values of the VST only the ones I exported and not a bunch of useless ones too”

Besides, the maximum parameters which is by default 64 does not work anyway because I managed to export a panel with 170+ modulators just fine. Therefore it seems that maximum value is really a minimum value of exported parameters because if less than 64, you will have 64 in the output in total, if more than 64 they will export all the ones you have (i.e., more than 64).

**Comment by damiensellier** [comment]
I think I know why the parameter "Max exported VST params" **ctrlrMaxExportedVstParameters** doesn't work properly. 
It's a Ctrlr preference not a panel one.
If you export a panel as vst restricted instance, from the function  getNumModulators() the highest vstindex should set the limit. But it's not if the vstindex highest number is above 64. From what I can see, it falls back to the default settings from global Ctrlr preferences (64) : 

`	overridesTree.setProperty (Ids::ctrlrMaxExportedVstParameters, 64, 0);`

```
int CtrlrProcessor::getNumParameters()
{
    if (ctrlrManager)
        return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters)));
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}
```

CtrlrMacros.h

**#define	CTRLR_DEFAULT_PARAMETER_COUNT	128**


```
int CtrlrManager::getNumModulators(const bool onlyVstParameters)
{
	if (onlyVstParameters)
	{
		if (ctrlrManagerVst.get())
			return (ctrlrManagerVst->getLargestIndex() + 1);
		else
			return (CTRLR_DEFAULT_PARAMETER_COUNT);
	}
	else
	{
		return (ctrlrModulators.size() + 1);
	}
}
```

I think the ctrlrMaxExportedVstParameters parameter is useless and should be removed unless it is declared at the panel level.

To confirm, can you please check if you have 64 or 128 paramaters in Cubase?

**Comment by damiensellier** [comment]
PS : Cubase shows 64 parameters anyway 0 to 63

![Capture d’écran, le 2024-07-03 à 14 33 00](https://github.com/RomanKubiak/ctrlr/assets/55164385/9bc8f068-473e-4e67-96c3-028366b9aa2f)

**Comment by damiensellier** [comment]
It can't work because it uses the comparator **jmax** which is supposed to return the highest value between the highest vstindex and the default 64. if you have 4 parameters, 4 < 64 so the number of controlled passed to the host will be 64 anyway.

```
int CtrlrProcessor::getNumParameters()
{
    if (ctrlrManager)
        // return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters)));
        return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters)));
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}
```

We don't need **jmax**, but we need **jmin**

```
/** Returns the larger of two values. */
template <typename Type>
constexpr Type jmax (Type a, Type b)                                   { return a < b ? b : a; }
```

i'll try with jmin  and see if it works...

**Comment by damiensellier** [comment]
or even without comparator and just get the max vstindex value : 

```
int CtrlrProcessor::getNumParameters()
{
    if (ctrlrManager)
        // return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters)));
        return (ctrlrManager->getNumModulators(true)); // Updated v5.6.31.
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}
```

**Comment by dervur** [comment]
I think just using the maximum vstindex value is the most reasonable thing, and that, as you said before ctrlrMaxExportedVstParameters should be deleted. It just makes everything confusing in my opinion and it does not make sense to me that someone would want to export less values than what they  actually created (and surely they do not want more).

I'll try to build a version tomorrow with the code in your last comment to see if it works as expected. I'll write a comment tomorrow to say what is the outcome.

**Comment by damiensellier** [comment]
@dervur it will work well for exported instance if you set everything properly beforehand. but it won't work as intended if you just load panel files in your ctrlr.vst.
Up to you...

**Comment by damiensellier** [comment]
I'll try that, to make everybody happy :) : 

```
int CtrlrProcessor::getNumParameters()
{
    if (ctrlrManager)
        if (ctrlrManager->isSingleInstance())
        {
            return (ctrlrManager->getNumModulators(true)); // Added v5.6.31.
        }
        else
        {
        return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters))); // updated 5.6.31 because VST Host was returning 64 params most of the time since panels hardly have more than 64 parameters passed as vst controls
        }
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}
```

**Comment by dervur** [comment]
> @dervur it will work well for exported instance if you set everything properly beforehand. but it won't work as intended if you just load panel files in your ctrlr.vst. Up to you...

Yeah that is my plan, I do not really care for the VST Ctrlr, I use that only to export instances, I do not edit or use hardware from there anyway

**Comment by damiensellier** [comment]
**FIXED** 
I got it working with the following statement : 

```
int CtrlrProcessor::getNumParameters() // Updated 5.6.31
{
    if (ctrlrManager)
        if (ctrlrManager->isSingleInstance())
        {
            return (ctrlrManager->getNumModulators(true)); // Added v5.6.31. 
        }
        else
        {
        return (jmax(ctrlrManager->getNumModulators(true), (int)overridesTree.getProperty (Ids::ctrlrMaxExportedVstParameters))); // Updated 5.6.31.
        }
    else
        return (CTRLR_DEFAULT_PARAMETER_COUNT);
}

```

When opening a panel in ctrlrx.vst we have 64 parameters ready to go as default : 

![Capture d’écran, le 2024-07-03 à 16 16 15](https://github.com/RomanKubiak/ctrlr/assets/55164385/19fbd59e-b0ab-4361-8617-cdd0b6415967)

When using a panel as vst instance we only have the max vstindex number of parameters passed to the host (here 4): 
![Capture d’écran, le 2024-07-03 à 16 18 52](https://github.com/RomanKubiak/ctrlr/assets/55164385/74b06036-d012-4d34-8e1a-80e17d89b4e9)

Hope it helps.
Damien

**Comment by dervur** [comment]
That’s amazing! Thank you so much!

**Comment by dervur** [comment]
Amazing! Thank you so much!

**Comment by damiensellier** [comment]
Thanks, I prefer this way too, I don't have 10 pages of useless parameters on my MIDI MCU controller now. that's cleaner.

![Capture d’écran, le 2024-07-03 à 16 32 14](https://github.com/RomanKubiak/ctrlr/assets/55164385/24282b6a-d49b-4960-8245-b2acf88209b8)

VS 

![Capture d’écran, le 2024-07-03 à 16 31 01](https://github.com/RomanKubiak/ctrlr/assets/55164385/20af5bff-7106-4209-b632-d2c0e06b6c88)
