### ISSUE TITLE
CtrlrX stopped working on Windows... It does not open at all

### ISSUE THREAD

**Issue by dervur** [RomanKubiak/ctrlr#658]
Hello there!

All of a sudden today CtrlrX stopped working, it is not opening anymore. I even tried installing and opening older versions. I'm talking of the exe file, if I install Ctrlr from ctrlr.org, it opens fine, but this does not support some things of the panel I was working on.

Somebody knows how to fix this issue? The app does not open at all.
I even tried to build it but Visual Studio gives me around 2000 errors.
I just feel like all the work I was doing has been lost... I can't understand why it is not opening when this morning it was working fine. Of course I tried restarting my laptop but to no avail.

Does anybody have no idea why all CtrlrX executables stopped working all of a sudden after me using them for about a week with no issues?

Cheers,
Samuele

**Comment by dervur** [comment]
Update: even building it does not open it, however, I noticed that when I try to run it, it appears in the background process for one second and then disappears... I think the problem is that my laptop went to sleep while CtrlrX was open and somehow broke it no matter if I build it or what version it is, it always tries to open it as a background process and then disappear...

If anybody ever had this happening please let me know how you solved it. If I install Ctrlr it opens fine so it seems to be an issue with the .exe compiled by VS...

**Comment by dervur** [comment]
Found the issue, it was with the settings file being corrupt for one panel. 
The path in windows where you will find the files is: `C:\Users\_username_\AppData\Roaming`
Here I found two folder Ctrlr and Ctrlr Panel, I don't know which one is which so I simply deleted all of their content and this solved the issue.

**Comment by dobo365** [comment]
Deleting the settings file is often solving the issue (keep a copy of the last one in case of).
I had it myself this week but I'm changing from CtrlrX (new builds) and the good old 5.3.201 all the time.
So, a common settings file may become nuts ;-)
I will discuss with Damien to make a separate CtrlrX .settings file (or full folder). It is easily done (I know the files to change).
