### ISSUE TITLE
Deactivate buttons when one is pressed

### ISSUE THREAD

**Issue by dervur** [RomanKubiak/ctrlr#661]
Hello there,

I'm doing a controller for which I want to deactivate some buttons when one is pressed. They are 10 buttons in total, but for now I'm testing only for two. I can't seem to make it work tough, Ctrlr crashes each time I press the button, so I think I did some mistake in my LUA script.
Does anybody know what am I doing wrong?
This script is called when the modulator value changes.

```
function soloButtonDeactivate()

    local p1 = panel:getModulatorByName("Solo_Part-1"):getModulatorValue()
    local p2 = panel:getModulatorByName("Solo_Part-2"):getMOdulatorValue()

    if p1=='On' then
        panel:getModulatorByName("Solo_Part-2"):getComponent():setEnabled(false)
    end

    if p2=='On' then
        panel:getModulatorByName("Solo_Part-1"):getComponent():setEnabled(false)
    end
  
end
```

**Comment by damiensellier** [comment]
Did you try creating a group of buttons and set them as radio?

![Capture d’écran, le 2024-07-02 à 14 12 19](https://github.com/RomanKubiak/ctrlr/assets/55164385/4d154138-b91f-4d36-9595-0c14bd8f3f40)

If they are grouped as radio buttons if you change value on 1 the other will be set to false

**Comment by damiensellier** [comment]
This is the regular way of doing it:
![Capture d’écran, le 2024-07-02 à 14 17 43](https://github.com/RomanKubiak/ctrlr/assets/55164385/feb0ca8a-23b5-4392-95cf-a2fcfa7971ee)

[radio-button-group_1_0_2024-07-02_14-15.panel.zip](https://github.com/user-attachments/files/16072757/radio-button-group_1_0_2024-07-02_14-15.panel.zip)

And another way with "onValueChange" LUA scripts:
![Capture d’écran, le 2024-07-02 à 14 17 29](https://github.com/RomanKubiak/ctrlr/assets/55164385/4495f14e-c26a-4cf3-a980-a851a0858b46)
This one is best if you want to force values on startup.
[Radio-2-onValueChange_2_3_using-onvalueChange_2020-08-11_17-40-2.bpanelz.zip](https://github.com/user-attachments/files/16072793/Radio-2-onValueChange_2_3_using-onvalueChange_2020-08-11_17-40-2.bpanelz.zip)

**Comment by damiensellier** [comment]
BTW it's better to post this kind of question in the [discussion section of this github](https://github.com/RomanKubiak/ctrlr/discussions) because here it's more about issues and bugs related to the source code of Ctrlr. People never look at the issue section... you'll get more audience there!
Feel free to ask anything there ;)
Damien

**Comment by dervur** [comment]
Hi Damien, sorry I didn't know that, I'll post there next time.
This seems to be what I want graphically, but while using the midi monitor I can see that once I click on a new button and the other goes off there is no MIDI output from the one that went off, only from the one going on. I know per certain that this would not work in my case.
I'm doing a controller for Volca Sample, and basically once a part is soloed, you can not solo other parts until you "unsolo" that part first. So in order for the radio button way to work the midi output should first deactivate the solo from one track and then solo the one that was pressed... Idk if what I said makes sense.

Basically, the way I would manually need to do it is (consider that the track is soloed and unsoloed everytime on that channel and CC there is a zero, it basically toggles the solo button for every zero):
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/f0139946-d467-4dc4-b981-c2b09fc2479c)
In this wat it would work, the first zero in Ch.2 solos Part 2, the second zero unsolos it, the zero in Ch.4 solos channel 4.
Here I clicked the solo button on the panel, clicked it again and then clicked the one for part 4.

If I sue the radio button to jump from one section to the other, this is the output:
![image](https://github.com/RomanKubiak/ctrlr/assets/77355362/c0d94296-5a3f-4661-998c-576053bf5485)
Here I clicked on the solo button for part 2, then I clicked the one in part 4.
Graphically on the panel it does what I want it to do, but by looking at the MIDI output I know for sure it will not work, the result will be part 2 remaining soloed and the panel showing part 4 soloed instead.

Another complications is that these buttons were already parts of different groups, once I saved and opened the panels they were taken out of these groups, so I don't think the radio button is part of the solution...

EDIT: I noticed that even if they are part of different groups, setting radio group to 1 allowed them to work as radio button anyway, so the issue remains the MIDI output only.

**Comment by damiensellier** [comment]
The fact the other values are not sent is a bug. I'll look into it because if all members of the radio button grp are "Send Midi from other members of the group" it should do what it says .

![Capture d’écran, le 2024-07-02 à 15 15 53](https://github.com/RomanKubiak/ctrlr/assets/55164385/39928a01-bd8e-4fe9-80e1-8270413bf59c)

The 2nd panel will do what you need because you can assign different midi messages when the value change. I did it already.

**Comment by dervur** [comment]
Yes the "Send midi from other members of the group" is selected.

I will take a look tomorrow at the other panel, I wasn't using it because I noticed that if you deselect one radio button you are not able to select other ones until you reselect the one you deselected.

**Comment by damiensellier** [comment]
Well, I just checked and "Send midi from other members of the group"  which is the property **componentRadioGroupNotifyMidi** is just a placeholder, nothing is assigned to it, no function, nothing...

**Comment by dervur** [comment]
Well... In the end this thread was made in the right post since a "bug" was found.

In panel 2 I think I would not have what I want to work properly because it sends a zero to all the other parts after sending it to the one I want to unsolo, so after it sends the zero to the one that was zeroed it will solo the next one.

What is the command to get a value? Because `panel:getModulatorByName("Solo_Part-1"):getModulatorValue()` seems to make Ctrlr crash, as well as `panel:getModulatorByName("Solo_Part-1"):getValue()` ...

Also is there a place where all these demo panels are? I think I could learn from these instead of asking plenty of questions.

**Comment by dervur** [comment]
I don't know what was wrong but now it works fine with `panel:getModulatorByName("Solo_Part-1"):getValue()` and if `p1==1 then`
I know above it was different but it was not working anyway with pi1==1.

@damiensellier should I leave the thread open for the radio button bug not sending the midi out of the other buttons? I noticed that in CtrlrModulator.cpp from line 111 to 145 there is a big chunk commented out that mentions the radio groups... I don't know if that might be the issue.

**Comment by dervur** [comment]
Also the way I made my button work is basically a radio button without the radio button function. It is inspired by the second panel you sent but instead of dumping all the other values as zeroes it first checks which one is on, and puts off only that.
Unfortunately I do not know any way to streamline my sending a message. Currently it sends 4 MIDI messages when you click on a button while another is selected (3 if none is selected).
E.g., you press button 1 while button 4 is on what happens is
- due to pressing the button that button is set to on, first midi message
- button 1 is set to off (in order to set it on every other button must be off), second midi message
- button 4 is set to off (the nest-if loop checks which button is on and sets off only that one), third midi message
- button 1 is set to on, fourth and last midi message

This is all because the script is run AFTER the button has changed state, if there is a way to run the script before that would delete two useless MIDI messages (the toggling on and off of the button you just pressed).
Anyway, I will test it later with the hardware, but looking at the MIDI monitor it should work just fine. Only issue might be if for some reason one of the messages is not received.

```
-- Called when a solo button is pressed to turn off the others

function soloButtonDeactivate(--[[ CtrlrModulator --]] mod, --[[ number --]] value, --[[ number --]] source)

    if source==4 then -- should stop this code running on start
	
	    local n=L(mod:getName())
        local p = panel:getModulatorByName(n):getValue()
	    local t={} --writing directly at definition does not accepts hunderscores and hypens, that's why I do it below
        t["Solo_Part-1"] = 0
        t["Solo_Part-2"] = 1
        t["Solo_Part-3"] = 2
        t["Solo_Part-4"] = 3
        t["Solo_Part-5"] = 4
        t["Solo_Part-6"] = 5
        t["Solo_Part-7"] = 6
        t["Solo_Part-8"] = 7
        t["Solo_Part-9"] = 8
        t["Solo_Part-10"] = 9

	    console("Unit Selected Value : "..n)

        if p==1 then
            panel:getModulatorByName(n):setValue(0, true) --set off the button that was just pressed
            console(n.." was set to zero")
	        for k,v in pairs(t)do
		        if k~=n then
                    p = panel:getModulatorByName(k):getValue() --get the value of other buttons
                    if p==1 then --if 1, then set it to 0
			            panel:getModulatorByName(k):setValue(0, true)
		                console(k.." was set to zero")
                    end
                end
	        end
            panel:getModulatorByName(n):setValue(1, true) --set on the button that was just pressed
            console(n.." was set to one")
        end
	end
	
    console('----------------------------')
end -- source ==4 (user clicked on a button - not lua generated
```

If Damien wants to keep this thread open because of the radio button bug we can leave this post open, otherwise we can close as I found the solution.

**Comment by damiensellier** [comment]
If you solved the problem you can close the ticket, I created one on the CtrlrX issue repo : 
https://github.com/damiensellier/CtrlrX/issues/30
Thanks for finding the radio group problem.

**Comment by damiensellier** [comment]
CtrlrModulator.cpp from line 111 to 145 : This is one of the rare comment Roman Kubiak wrote in this source code :)

**Comment by dervur** [comment]
Ok perfect, thank you very much again for the invaluable help!

**Comment by damiensellier** [comment]
You can send the midi message via LUA at the exact step you want to, instead of doing the LUA script to switch on/off and send the midi message from the button MIDI properties.

this is the new correct lua code to send midi message, just change it to your needs: 

`panel:sendMidiMessageNow(CtrlrMidiMessage(MemoryBlock({0xB0, 0x0C, CcValue}))`

you can use tokens into the message for midi channel if required etc 
`https://github.com/damiensellier/CtrlrX/wiki/SysEx-Token-List`

**Comment by dervur** [comment]
With the send MIDI message now it will not work because the script will always be called after the MIDI message has been sent unfortunately. But thank you anyway.
