### ISSUE TITLE
Lua methods referenced in panel callbacks get called on startup

### ISSUE THREAD

**Issue by fredzo** [RomanKubiak/ctrlr#7]
I need to start each methods referenced in panel callbacks with this code : 
    if panel:getBootstrapState() or panel:getProgramState() then
        return
    end
otherwise the code of the method is executed on panel load or on Ctrlr start.
In addition to that, event if I use the above code, all the callback methods are called the first time I launch an exported instance of my panel.

**Comment by rhaamo** [comment]
Bump for this issue.
I have got the same issue, at start the callbacks get called, you code snippet avoid that.

May this be fixed in Ctrlr if a bug ?

**Comment by fredzo** [comment]
Fixed by https://github.com/RomanKubiak/ctrlr/pull/67/commits/23c6fbb69d9d609ca72fec4b069bcef38cb44015
