### ISSUE TITLE
ENH: add ability to display external images within a custom component in Ctrlr

### ISSUE THREAD

**Issue by dobo365** [RomanKubiak/ctrlr#70]
Hi,
 I'd like to get within Ctrlr the Juce functions allowing to display external images (thus images not stored within the Resources tab of the panel) on a panel.
This is available in Juce with the ImagePreviewComponent Class.

If someone can describe me how to do that I can adapt the file in the github repository (I have programming skills but don't know how Ctrlr is built, how it relates to Juce, how is the link made between Juce functions and Ctrlr in order to make them available, etc...
So, if I get some explanations, I can find time to contribute to this nice project.
Thx!

**Comment by RomanKubiak** [comment]
Image drawing in Lua is there and always was, please have a look at the DEMO/Rendering panel example, you will find all graphics examples there

**Comment by dobo365** [comment]
Well, I looked at Rendering already before but didn't find what I'm after.
I'd like to be able to open .jpg files on the disk and display them within
a panel.
This without having the images as resources beforehand.
If it is in render.panelz can you please indicate me where (I'm using
5.3.201 maybe you added this in a more recent version)
Thx!

2018-06-07 15:15 GMT+02:00 Roman Kubiak <notifications@github.com>:
