### ISSUE TITLE
Linux Build Instructions Not Current

### ISSUE THREAD

**Issue by will-riley** [RomanKubiak/ctrlr#73]
This is in the docs:

"A build.sh script is provided in Builds/Generated/Linux/Standalone, a symlink of that script is location in Builds/Generated/Linux/VST"

Those files don't exist. Unable to build. 
Thanks

**Comment by rhaamo** [comment]
Only the `stable` branch does have the scripts.

But since the VST sdk takedown it's impossible to build, and the current code doesn't seems to build at all with the current SDK as the 2.x seems to have been completly removed from availability.

**Comment by ViktorNova** [comment]
Ah, so the stable branch is not the main git branch - I didn't realize this until now

It is still pretty easy find the VST 2 SDK online, just sayin =)

**Comment by RomanKubiak** [comment]
all those files are now on the master branch and should build ctrlr
