### ISSUE TITLE
libbfd-2.28-system.so missing

### ISSUE THREAD

**Issue by muranyia** [RomanKubiak/ctrlr#75]
libbfd-2.28-system.so is missing in Ubuntu 16.04.6 LTS (Xenial)

ctrlr builds fine but won't start.

**Comment by ensonic** [comment]
Same on open-suse.
```
$ ./Ctrlr
./Ctrlr: error while loading shared libraries: libbfd-2.28-system.so:
$ locate libbfd
/usr/lib64/libbfd-2.32.so
```

**Comment by udaemon** [comment]
I have the same issue with this version here on antergos/arch.
it's always a version of libbfd that prevents Ctrlr resp. the vst-plugin from working.

if anybody has an idea ...
thanks!

**Comment by udaemon** [comment]
I just stumbled upon this thread about the same issue with Ctrlr 6.0.1: http://ctrlr.org/forums/users/arcangeli/replies/

right now I don't have time to figure out if it helps but the hints do seem helpful.

**Comment by dromer** [comment]
I did a ```sudo ln -s /usr/lib/x86_64-linux-gnu/libbfd-2.31.1-system.so /usr/lib/x86_64-linux-gnu/libbfd-2.28-system.so``` to make the latest build work (that's ```Ctrlr-x86_64-6.0.1.sh```).

**Comment by muranyia** [comment]
@dromer yes, or you could use `patchelf --replace-needed` in order not to mess with your system. But then I get:
```
./Ctrlr: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./Ctrlr)
```

**Comment by RomanKubiak** [comment]
i'm linking to whatever the latest ubuntu provides, different distros might use different lib versions this is when you have to build ctrlr yourself, i'm considering using snap or some similar way to distribute ctrlr but i'm far away from it
