### ISSUE TITLE
can this be built on linux?

### ISSUE THREAD

**Issue by ekg** [RomanKubiak/ctrlr#78]
I'm unable to run Ctrlr on linux:

```
erik@foldy [03:03:05 PM] [~/Downloads/Ctrlr] 
-> % ./Ctrlr                      
./Ctrlr: error while loading shared libraries: libbfd-2.28-system.so: cannot open shared object file: No such file or directory
```

I've tried to build it. I checked out the stable branch. I get this far:

```
erik@foldy [03:01:29 PM] [~/ctrlr/Builds/LinuxMakefile] [stable *]
-> % ./build.sh                           
CTRLR[linux]: Building for x86_64, JOBS 
CTRLR[linux]: PCH not rebuilt, use -f to force
CTRLR[linux]: Build now

Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling darwin_usb.c
Compiling descriptor.c
In file included from ../../JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp:27:0,
                 from ../../JuceLibraryCode/include_juce_audio_plugin_client_VST2.cpp:9:
../../JUCE/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:95:10: fatal error: pluginterfaces/vst2.x/aeffect.h: No such file or directory
 #include "pluginterfaces/vst2.x/aeffect.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:359: recipe for target 'build/intermediate/Release/include_juce_audio_plugin_client_VST2_dd551e08.o' failed
make: *** [build/intermediate/Release/include_juce_audio_plugin_client_VST2_dd551e08.o] Error 1
make: *** Waiting for unfinished jobs....
CTRLR[linux]: build failed
```

How should we build this on linux?

**Comment by udaemon** [comment]
Hi, I tried the same on my system (antergos/arch linux) and building quit likewise. but in arch/aur repos you find a recent vst-sdk package and it brings the files needed here. so, the vst-sdk being installed I have these files in `/usr/include/vst36/pluginterfaces/vst2.x/aeffect.h` (and likewise aeffectx.h). what I did is to symlink the files with the place they are looked for in the build script here:
`ln -s /usr/include/vst36/pluginterfaces/vst2.x/aeffect.h /usr/include/pluginterfaces/vst2.x/aeffect.h`

building still fails, but for other reasons I have not figured out, yet.
maybe this helps for now!?

**Comment by ViktorNova** [comment]
I am having this same issue - I have tried putting the VST2 SDK files into /usr/include/pluginterfaces/vst2.x/, but am still getting the error ````No rule to make target '../../JuceLibraryCode/include_juce_audio_plugin_client_VST2.cpp'````

What to do?

**Comment by muranyia** [comment]
I also had a problem with `boost` sources not being unzipped (stable branch).

**Comment by muranyia** [comment]
And then... it builds successfully.
The success factors seem to be:

- Use the `stable` branch
- Enable the 'executable' bit for the `.sh` files as wellas for the `post-commit` script
- Use `dos2unix` on the `.sh` files if you get errors for `\r` characters (not needed for the `stable` branch)
- Unzip `boost.zip` to `Source/Misc`

**Comment by RomanKubiak** [comment]
please use the master branch now i removed the stable one, all development is done on master
