### ISSUE TITLE
font size gets set to 0 after undo

### ISSUE THREAD

**Issue by ndrik** [RomanKubiak/ctrlr#8]
Most of the time, especially after moving or modifying the size of a component and "undoing" the changes, some font size gets set to 0. Either the label name, or the slider value font. This happens on OSx at least.

**Comment by RomanKubiak** [comment]
Could you be a bit more specific here, or attach an example panel that shows this. What component should i test it on to see this behavior ?

**Comment by ndrik** [comment]
Hello Roman,

You can test this behaviour on the attached MKS70 panel. If you change the color of a component, or most of the other display options, text size, value font, the bubble value text disappears. Sometimes this also happens with the labels.
It might be because of me building this panel since a quite old version of ctrlr though. But, now that it’s 99% working, I’d rather not start it from scratch again :)

Please let me know if I can be of some more help. I can record a small movie if you want too.

Btw, I can’t thank you enough for the hard work you’ve put into this project. It’s a steep learning curve, but it does what it’s supposed to do surprisingly well!

Cheers,

H. van Boetzelaer
////////////////////////////////////////////////////////////////////////////////////////////////
||||||	architect EPF & parametric design consultancy
|||||| 	mobile:	+41763652683     
|||||| 	www: 	http://www.proceduralstrategies.net
|||||| 	mail: 	hvanboetzelaer@gmail.com
////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by ndrik** [comment]
Realized the panel didn't get attached. Here's a proper link: http://bit.ly/1Lbz9Yg

**Comment by fredzo** [comment]
Should be fixed by this commit : https://github.com/RomanKubiak/ctrlr/commit/22f52357c1642c7ad0c6f3ec0c61ace9836ce588
Don't hesitate to reopen if the bug is still here.

**Comment by ndrik** [comment]
Would LOVE to have a chance to test this.
Any chance there could be a new OSX build? I tried on my own, but get error
after error and don’t know where to start.

H. van Boetzelaer

*////////////////////////////////////////////////////////////////////////////////////////////////*


*|||||| architect EPF & parametric design consultancy*

*||||||  tel: +41763652683 <//+41763652683>     *

*||||||  www: http://www.proceduralstrategies.net
<http://www.proceduralstrategies.net/>*

*||||||  mail:  **hvanboetzelaer@gmail.com* <hvanboetzelaer@gmail.com>

*////////////////////////////////////////////////////////////////////////////////////////////////*

From: fredzo <notifications@github.com> <notifications@github.com>
Reply: RomanKubiak/ctrlr
<reply@reply.github.com>
<reply@reply.github.com>
Date: 27 October 2017 at 10:08:59
To: RomanKubiak/ctrlr <ctrlr@noreply.github.com> <ctrlr@noreply.github.com>
Cc: ndrik <hvanboetzelaer@gmail.com> <hvanboetzelaer@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [RomanKubiak/ctrlr] font size gets set to 0 after undo (#8)

Should be fixed by this commit : 22f5235
<https://github.com/RomanKubiak/ctrlr/commit/22f52357c1642c7ad0c6f3ec0c61ace9836ce588>
Don't hesitate to reopen if the bug is still here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RomanKubiak/ctrlr/issues/8#issuecomment-339903379>, or mute
the thread
