### ISSUE TITLE
Linux scripts are in DOS format and not runnable

### ISSUE THREAD

**Issue by ViktorNova** [RomanKubiak/ctrlr#80]
I have this issue on both head and stable branches, bash scripts do not run because they were saved with DOS/Windows formatting, and spit out all kinds of errors when attempting to execute them. I have to convert all of them using ````dos2unix```` and then they run 

This has so far been the case for these files:
````
Scripts/gen_rsrc.sh
Scripts/git-revision.sh
Scripts/post-commit
````

OS: Ubuntu 19.10 64bit

**Comment by muranyia** [comment]
The scripts are DOS in the master branch and UNIX in the stable branch.

Additionally, the `.sh` files are not executable in either branch.

**Comment by RomanKubiak** [comment]
should be fixed now
