### ISSUE TITLE
Ctrlr.org security certificate expired

### ISSUE THREAD

**Issue by Andy2No** [RomanKubiak/ctrlr#83]
For the last week or so, any attempt to visit the Ctrlr.org website, results in this error message:

"
Your connection is not secure

The owner of ctrlr.org has configured their web site improperly. To protect your information from being stolen, Waterfox has not connected to this web site.

Learn more…

Report errors like this to help Mozilla identify and block malicious sites
"

Since the site is based on Wordpress, I'm not comfortable with adding an exception.  Is there a plan to fix this?

**Comment by larsnaesbye** [comment]
Looks like the certificate is issued to [ctrlr.org](ctrlr.org) only and not [www.ctrlr.org](www.ctrlr.org), even though that DNS entry points to the same IP address.

**Comment by RomanKubiak** [comment]
fixed
