### ISSUE TITLE
www.ctrlr.org down?

### ISSUE THREAD

**Issue by styro2000** [RomanKubiak/ctrlr#87]
i tryed to visit https://www.ctrlr.org/ the last days, seems to be down...
is there a other way to read the docs?

many thanks for Your help and the great work!
all the best
styro

**Comment by christofmuc** [comment]
It seems to me the website is up, but it has a certificate error, where your browser rightfully so cautions you to visit the website. My Firefox does the same, but when I accept the risk it will show me the website. Seems the maintenance of the website has some problem.

**Comment by styro2000** [comment]
i accepted the certification risk some time ago and it worked, so this is not the problem.  doesnt work on chrome and even ping on www.ctrlr.org is dead.. tryed with different providers, OSs , browsers and devices :-(

**Comment by RomanKubiak** [comment]
this should be fixed now

**Comment by christofmuc** [comment]
Can confirm it works now - I had to delete the cache of my Firefox, and then it accepted the new certificate! And it says I visited that website 53 times ;-)
