### ISSUE TITLE
Unable to download deprecated panels

### ISSUE THREAD

**Issue by Sch-LikA** [RomanKubiak/ctrlr#88]
Hi, I am reinstalling my vintage Motu Midi Mixer 7s and found out there is a deprecated panel for it. Unfortunately downloading does not work, The download url is https://ctrlr.org/panels_deprecated/?get&idx=79 which shows the /panels_deprecated/ index but does not download anything.

Could you please check it ? Thank !!

**Comment by RomanKubiak** [comment]
sorry i can't help with that, you can contact the authors of the panels if they still have them some of the are in the panels repo on github https://github.com/RomanKubiak/panels
