### ISSUE TITLE
ctrlr stable does not compile on debian buster / error 1 at keys_f237af18.o

### ISSUE THREAD

**Issue by tomlem** [RomanKubiak/ctrlr#92]
CTRLR[linux]: Building for x86_64, JOBS 16
CTRLR[linux]: Compile PCH
stadfx.h
stdafx_luabind.h
CTRLR[linux]: Build now

Compiling keys.cpp
Compiling CtrlrPanelResourceManager.cpp
Compiling CtrlrPanelUndoManager.cpp
Compiling CtrlrPanelSchemeMigration.cpp
Compiling CtrlrStandaloneApplication.cpp
Compiling CtrlrStandaloneWindow.cpp
Compiling CtrlrFontManager.cpp
Compiling CtrlrIDManager.cpp
Compiling CtrlrLog.cpp
Compiling CtrlrProperties.cpp
Compiling CtrlrSysexProcessor.cpp
Compiling CtrlrSysexProcessorOwned.cpp
Compiling CtrlrSysexToken.cpp
Compiling CtrlrUtilitiesGUI.cpp
Compiling CtrlrUtilities.cpp
Compiling stdafx.cpp
In file included from ../../Source/Misc/keys.cpp:5:
/usr/include/X11/Xlib.h:199:9: error: reference to ‘Font’ is ambiguous
         Font font;         /* default text font for text operations */
         ^~~~
In file included from ../../JUCE/modules/juce_graphics/juce_graphics.h:134,
                 from ../../JUCE/modules/juce_audio_devices/juce_audio_devices.h:58,
                 from ../../JuceLibraryCode/JuceHeader.h:18,
                 from ../../Source/Core/stdafx.h:12,
                 from ../../Source/Misc/keys.cpp:1:
../../JUCE/modules/juce_graphics/fonts/juce_Font.h:42:17: note: candidates are: ‘class juce::Font’
 class JUCE_API  Font
                 ^~~~
In file included from /usr/include/X11/Xlib.h:44,
                 from ../../Source/Misc/keys.cpp:5:
/usr/include/X11/X.h:100:13: note:                 ‘typedef XID Font’
 typedef XID Font;
             ^~~~
In file included from ../../Source/Misc/keys.cpp:5:
/usr/include/X11/Xlib.h:469:9: error: reference to ‘Time’ is ambiguous
         Time time;
         ^~~~
In file included from ../../JUCE/modules/juce_core/juce_core.h:286,
                 from ../../JUCE/modules/juce_audio_basics/juce_audio_basics.h:52,
                 from ../../JuceLibraryCode/JuceHeader.h:17,
                 from ../../Source/Core/stdafx.h:12,
                 from ../../Source/Misc/keys.cpp:1:
../../JUCE/modules/juce_core/time/juce_Time.h:36:17: note: candidates are: ‘class juce::Time’
 class JUCE_API  Time
                 ^~~~
In file included from /usr/include/X11/Xlib.h:44,
                 from ../../Source/Misc/keys.cpp:5:
/usr/include/X11/X.h:77:23: note:                 ‘typedef long unsigned int Time’
 typedef unsigned long Time;
                       ^~~~
In file included from ../../Source/Misc/keys.cpp:5:
/usr/include/X11/Xlib.h:565:2: error: reference to ‘Time’ is ambiguous
  Time time;  /* milliseconds */

(...)

Compiling stdafx_luabind.cpp
make: *** [Makefile:557: build/intermediate/Release/keys_f237af18.o] Fout 1
make: *** Wachten op onvoltooide taken...
CTRLR[linux]: build failed

**Comment by Andy2No** [comment]
The chances are, you need a different version of the compiler (e.g. gcc).

I've used gcc on Windows, to build STM32 projects (as part of gnu tools for ARM embedded processors).  You generally need the same exact version number that was used to build the project originally - so I now have a couple off different versions of it installed, for different projects.

**Comment by RomanKubiak** [comment]
this is a matter of precompiled headers and the fact that im using them, try the master branch from now it might help

**Comment by tomlem** [comment]
It still is not compiling. Seems to me due to problems with libbfd (in debian buster the gnu libbfd library is part of binutils-dev 2.31.1-16)

/ctrlr/Builds/LinuxMakefile$ make
Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling compat.c
Compiling core.c
Compiling darwin_usb.c
Compiling descriptor.c
Compiling enums.c
Compiling hotplug.c
Compiling io.c
Compiling linux_udev.c
Compiling linux_usbfs.c
Compiling poll_posix.c
Compiling poll_windows.c
Compiling strerror.c
Compiling structs.c
Compiling sync.c
Compiling threads_posix.c
Compiling threads_windows.c
Compiling usb.c
Compiling windows_usb.c
Compiling lua.c
Compiling class.cpp
Compiling class_info.cpp
Compiling class_registry.cpp
Compiling class_rep.cpp
Compiling create_class.cpp
Compiling error.cpp
Compiling exception_handler.cpp
Compiling function.cpp
Compiling function_introspection.cpp
Compiling inheritance.cpp
Compiling link_compatibility.cpp
Compiling lua51compat.cpp
Compiling object_rep.cpp
Compiling open.cpp
Compiling operator.cpp
Compiling pcall.cpp
Compiling scope.cpp
Compiling set_package_preload.cpp
Compiling shared_ptr_converter.cpp
Compiling stack_content_by_name.cpp
Compiling weak_ref.cpp
Compiling wrapper_base.cpp
Compiling keys.cpp
Compiling libr-bfd.c
../../Source/Misc/libr-bfd.c: In function ‘keep_symbol’:
../../Source/Misc/libr-bfd.c:111:28: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
     bfd_section_size(chkscn) == 0
                            ^
../../Source/Misc/libr-bfd.c:111:5: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
     bfd_section_size(chkscn) == 0
     ^~~~~~~~~~~~~~~~
     bfd_set_gp_size
../../Source/Misc/libr-bfd.c:111:5: note: each undeclared identifier is reported only once for each function it appears in
../../Source/Misc/libr-bfd.c: In function ‘setup_sections’:
../../Source/Misc/libr-bfd.c:168:25: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
    bfd_section_size(iscn) == 0
                         ^
../../Source/Misc/libr-bfd.c:168:4: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
    bfd_section_size(iscn) == 0
    ^~~~~~~~~~~~~~~~
    bfd_set_gp_size
../../Source/Misc/libr-bfd.c:196:5: error: too few arguments to function ‘bfd_set_section_size’
    !bfd_set_section_size(oscn, iscn->size)
     ^~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1915:13: note: declared here
 bfd_boolean bfd_set_section_size
             ^~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:206:29: error: macro "bfd_section_vma" requires 2 arguments, but only 1 given
   vma = bfd_section_vma(iscn);
                             ^
../../Source/Misc/libr-bfd.c:206:9: error: ‘bfd_section_vma’ undeclared (first use in this function); did you mean ‘bfd_scan_vma’?
   vma = bfd_section_vma(iscn);
         ^~~~~~~~~~~~~~~
         bfd_scan_vma
../../Source/Misc/libr-bfd.c:212:5: error: too few arguments to function ‘bfd_set_section_vma’
    !bfd_set_section_vma(oscn, vma)
     ^~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1686:1: note: declared here
 bfd_set_section_vma (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr, bfd_vma val)
 ^~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c:224:63: error: macro "bfd_section_alignment" requires 2 arguments, but only 1 given
    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
                                                               ^
../../Source/Misc/libr-bfd.c:224:37: error: ‘bfd_section_alignment’ undeclared (first use in this function); did you mean ‘bfd_set_section_alignment’?
    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
                                     ^~~~~~~~~~~~~~~~~~~~~
                                     bfd_set_section_alignment
../../Source/Misc/libr-bfd.c:224:5: error: too few arguments to function ‘bfd_set_section_alignment’
    !bfd_set_section_alignment(oscn, bfd_section_alignment(iscn))
     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1694:1: note: declared here
 bfd_set_section_alignment (bfd * abfd ATTRIBUTE_UNUSED, asection * ptr,
 ^~~~~~~~~~~~~~~~~~~~~~~~~
../../Source/Misc/libr-bfd.c: In function ‘build_output’:
../../Source/Misc/libr-bfd.c:301:31: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
   size = bfd_section_size(iscn);
                               ^
../../Source/Misc/libr-bfd.c:301:10: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_set_gp_size’?
   size = bfd_section_size(iscn);
          ^~~~~~~~~~~~~~~~
          bfd_set_gp_size
../../Source/Misc/libr-bfd.c: In function ‘add_section’:
../../Source/Misc/libr-bfd.c:566:4: error: too few arguments to function ‘bfd_set_section_flags’
   !bfd_set_section_flags(scn, SEC_HAS_CONTENTS | SEC_DATA | SEC_IN_MEMORY)
    ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../Source/Misc/include/libr.h:30,
                 from ../../Source/Misc/libr-bfd.c:28:
/usr/include/bfd.h:1899:13: note: declared here
 bfd_boolean bfd_set_section_flags
             ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:562: build/intermediate/Debug/libr-bfd_fc7a9004.o] Fout 1

**Comment by RomanKubiak** [comment]
try looking into Source/Misc/include/libr.h there is a macro on top
#define HAVE_BFD_2_34 1
try to undefine it and see if that helps

**Comment by tomlem** [comment]
**It compiles!** I now have to test the build. Are the compiled progras in Packaging/Linux?

/ctrlr/Builds/LinuxMakefile$ ./build.sh
CTRLR[linux]: Building for x86_64, JOBS 16
CTRLR[linux]: PCH not rebuilt, use -f to force
CTRLR[linux]: Build now

Compiling libr-bfd.c
Compiling libr.c
Compiling CtrlrLuaFile.cpp
Compiling CtrlrLuaMemoryBlock.cpp
Compiling CtrlrLuaRectangle.cpp
Compiling LComponents.cpp
Compiling LAudio.cpp
Compiling LCore.cpp
Compiling LGraphics.cpp
Compiling LJuce.cpp
Compiling LMemory.cpp
Compiling CtrlrLuaMethod.cpp
Compiling CtrlrLuaMethodManager.cpp
Compiling CtrlrLuaMethodManagerCalls.cpp
Compiling CtrlrLuaAudioConverter.cpp
Compiling CtrlrLuaDebugger.cpp
Compiling CtrlrLuaManager.cpp
Compiling CtrlrLuaObject.cpp
Compiling CtrlrLuaObjectWrapper.cpp
Compiling CtrlrLuaPanelCanvasLayer.cpp
Compiling CtrlrLuaUtils.cpp
Compiling CtrlrMIDIDevice.cpp
Compiling CtrlrMIDIDeviceManager.cpp
Compiling CtrlrMIDIFilter.cpp
Compiling CtrlrMidiInputComparator.cpp
Compiling CtrlrMidiInputComparatorMulti.cpp
Compiling CtrlrMidiInputComparatorSingle.cpp
Compiling CtrlrMidiMessage.cpp
Compiling CtrlrMidiMessageEx.cpp
Compiling CtrlrOwnedMidiMessage.cpp
Compiling CtrlrLinux.cpp
Compiling CtrlrMac.cpp
Compiling CtrlrNative.cpp
Compiling CtrlrWindows.cpp
Compiling CtrlrProcessor.cpp
Compiling CtrlrProcessorEditorForLive.cpp
Compiling CtrlrDocumentPanel.cpp
Compiling CtrlrEditor.cpp
Compiling CtrlrEditorApplicationCommands.cpp
Compiling CtrlrEditorApplicationCommandsHandlers.cpp
Compiling CtrlrEditorApplicationCommandsMenus.cpp
Compiling CtrlrSettings.cpp
Compiling CtrlrButton.cpp
Compiling CtrlrCustomButtonInternal.cpp
Compiling CtrlrHyperlink.cpp
Compiling CtrlrImageButton.cpp
Compiling CtrlrToggleButton.cpp
Compiling CtrlrGroup.cpp
Compiling CtrlrTabsComponent.cpp
Compiling CtrlrImage.cpp
Compiling CtrlrLabel.cpp
Compiling CtrlrLCDLabel.cpp
Compiling CtrlrFixedImageSlider.cpp
Compiling CtrlrFixedSlider.cpp
Compiling CtrlrImageSlider.cpp
Compiling CtrlrSlider.cpp
Compiling CtrlrSliderInternal.cpp
Compiling CtrlrFileListBox.cpp
Compiling CtrlrListBox.cpp
Compiling CtrlrMidiKeyboard.cpp
Compiling CtrlrProgressBar.cpp
Compiling CtrlrWaveform.cpp
Compiling CtrlrXYModulator.cpp
Compiling CtrlrXYSurface.cpp
Compiling CtrlrArrow.cpp
Compiling CtrlrCombo.cpp
Compiling CtrlrComponent.cpp
Compiling CtrlrComponentLuaRegistration.cpp
Compiling CtrlrComponentTypeManager.cpp
Compiling CtrlrCustomComponent.cpp
Compiling CtrlrFilmStripPainter.cpp
Compiling CtrlrLuaCodeTokeniser.cpp
Compiling CtrlrLuaMethodCodeEditor.cpp
Compiling CtrlrLuaMethodCodeEditorSettings.cpp
Compiling CtrlrLuaMethodDebuggerControls.cpp
Compiling CtrlrLuaMethodDebuggerInfo.cpp
Compiling CtrlrLuaMethodDebuggerPrompt.cpp
Compiling CtrlrLuaMethodDebuggerStackTrace.cpp
Compiling CtrlrLuaMethodDebuggerVars.cpp
Compiling CtrlrLuaMethodEditArea.cpp
Compiling CtrlrLuaMethodEditor.cpp
Compiling CtrlrLuaMethodEditorConsole.cpp
Compiling CtrlrLuaMethodEditorTabs.cpp
Compiling CtrlrLuaMethodFind.cpp
Compiling CtrlrMethodEditorTabCloseButton.cpp
Compiling CtrlrLuaConsole.cpp
Compiling CtrlrMIDIBuffer.cpp
Compiling CtrlrMIDIBufferEditor.cpp
Compiling CtrlrMIDICalculator.cpp
Compiling CtrlrMIDIMon.cpp
Compiling CtrlrMIDISettingsDevices.cpp
Compiling CtrlrMIDISettingsDialog.cpp
Compiling CtrlrMIDISettingsRouting.cpp
Compiling CtrlrPanelCanvas.cpp
Compiling CtrlrPanelCanvasHandlers.cpp
Compiling CtrlrPanelCanvasLayer.cpp
Compiling CtrlrPanelCanvasLayers.cpp
Compiling CtrlrPanelComponentProperties.cpp
Compiling CtrlrPanelEditor.cpp
Compiling CtrlrPanelLayerList.cpp
Compiling CtrlrPanelLayerListItem.cpp
Compiling CtrlrPanelModulatorList.cpp
Compiling CtrlrPanelModulatorListTree.cpp
Compiling CtrlrPanelProperties.cpp
Compiling CtrlrPanelResourceEditor.cpp
Compiling CtrlrPanelUtilities.cpp
Compiling CtrlrPanelViewport.cpp
Compiling CtrlrViewport.cpp
Compiling CtrlrPropertyComponent.cpp
Compiling CtrlrChildWindow.cpp
Compiling CtrlrChildWindowContainer.cpp
Compiling CtrlrChildWindowContent.cpp
Compiling CtrlrDialogWindow.cpp
Compiling CtrlrManagerWindowManager.cpp
Compiling CtrlrPanelWindowManager.cpp
Compiling CtrlrAbout.cpp
Compiling CtrlrComponentSelection.cpp
Compiling CtrlrLogViewer.cpp
Compiling CtrlrTextEditor.cpp
Compiling CtrlrValueMap.cpp
Compiling CtrlrValueTreeEditor.cpp
Compiling BinaryData.cpp
Compiling include_juce_audio_basics.cpp
Compiling include_juce_audio_devices.cpp
Compiling include_juce_audio_formats.cpp
Compiling include_juce_audio_plugin_client_utils.cpp
Compiling include_juce_audio_processors.cpp
Compiling include_juce_audio_utils.cpp
Compiling include_juce_core.cpp
Compiling include_juce_data_structures.cpp
Compiling include_juce_events.cpp
Compiling include_juce_graphics.cpp
Compiling include_juce_gui_basics.cpp
Compiling include_juce_gui_extra.cpp
Compiling include_juce_audio_plugin_client_Standalone.cpp
Linking Ctrlr - Shared Code
Linking Ctrlr - VST
Linking Ctrlr - Standalone Plugin
/usr/bin/ld: build/Ctrlr.a(lua_260ca39c.o): in function `os_tmpname':
lua.c:(.text+0x18400): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: build/Ctrlr.a(lua_260ca39c.o): in function `os_tmpname':
lua.c:(.text+0x18400): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CTRLR[linux]: build succeeded

**Comment by RomanKubiak** [comment]
Builds/LinuxMakefile/build

**Comment by tomlem** [comment]
It crashes.

Ctrlr.crash:

Ctrlr crash at: 31 Dec 2020 11:36:38
Stack trace:
./Ctrlr(+0x5f8337) [0x5634051e0337]
./Ctrlr(+0x53c454) [0x563405124454]
./Ctrlr(+0x5e4f9d) [0x5634051ccf9d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7fb5a2c04730]
./Ctrlr(+0x8575e3) [0x56340543f5e3]
./Ctrlr(+0x8579c4) [0x56340543f9c4]
./Ctrlr(+0x940204) [0x563405528204]
./Ctrlr(+0x9483a8) [0x5634055303a8]
./Ctrlr(+0x948da6) [0x563405530da6]
./Ctrlr(+0x86b9aa) [0x5634054539aa]
./Ctrlr(+0x85a094) [0x563405442094]
./Ctrlr(+0x85b49b) [0x56340544349b]
./Ctrlr(+0x85b58f) [0x56340544358f]
./Ctrlr(+0x53f190) [0x563405127190]
./Ctrlr(+0x53d69c) [0x56340512569c]
./Ctrlr(+0x53cea6) [0x563405124ea6]
./Ctrlr(+0x664f5e) [0x56340524cf5e]
./Ctrlr(+0x2815ea) [0x563404e695ea]
./Ctrlr(+0x281665) [0x563404e69665]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fb5a23ab09b]
./Ctrlr(+0x53c1aa) [0x5634051241aa]
